package com.jufan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BizAsset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.BIZ_TYPE
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.BIZ_TYPE_NAME
     *
     * @mbggenerated
     */
    private String bizTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.ASSET_NUMBER
     *
     * @mbggenerated
     */
    private String assetNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.ASSET_TYPE
     *
     * @mbggenerated
     */
    private String assetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    private String assetTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.MERCHANT_NAME
     *
     * @mbggenerated
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.ASSET_APPLY_TIME
     *
     * @mbggenerated
     */
    private Date assetApplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.INSTALLMENT_APPLY_TIME
     *
     * @mbggenerated
     */
    private Date installmentApplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.PERIOD
     *
     * @mbggenerated
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.PERIOD_LENGTH
     *
     * @mbggenerated
     */
    private String periodLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.ID
     *
     * @return the value of biz_asset.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.ID
     *
     * @param id the value for biz_asset.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.BIZ_TYPE
     *
     * @return the value of biz_asset.BIZ_TYPE
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.BIZ_TYPE
     *
     * @param bizType the value for biz_asset.BIZ_TYPE
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.BIZ_TYPE_NAME
     *
     * @return the value of biz_asset.BIZ_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getBizTypeName() {
        return bizTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.BIZ_TYPE_NAME
     *
     * @param bizTypeName the value for biz_asset.BIZ_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setBizTypeName(String bizTypeName) {
        this.bizTypeName = bizTypeName == null ? null : bizTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.ASSET_NUMBER
     *
     * @return the value of biz_asset.ASSET_NUMBER
     *
     * @mbggenerated
     */
    public String getAssetNumber() {
        return assetNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.ASSET_NUMBER
     *
     * @param assetNumber the value for biz_asset.ASSET_NUMBER
     *
     * @mbggenerated
     */
    public void setAssetNumber(String assetNumber) {
        this.assetNumber = assetNumber == null ? null : assetNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.ASSET_TYPE
     *
     * @return the value of biz_asset.ASSET_TYPE
     *
     * @mbggenerated
     */
    public String getAssetType() {
        return assetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.ASSET_TYPE
     *
     * @param assetType the value for biz_asset.ASSET_TYPE
     *
     * @mbggenerated
     */
    public void setAssetType(String assetType) {
        this.assetType = assetType == null ? null : assetType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.ASSET_TYPE_NAME
     *
     * @return the value of biz_asset.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getAssetTypeName() {
        return assetTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.ASSET_TYPE_NAME
     *
     * @param assetTypeName the value for biz_asset.ASSET_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setAssetTypeName(String assetTypeName) {
        this.assetTypeName = assetTypeName == null ? null : assetTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.MERCHANT_ID
     *
     * @return the value of biz_asset.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.MERCHANT_ID
     *
     * @param merchantId the value for biz_asset.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.MERCHANT_NAME
     *
     * @return the value of biz_asset.MERCHANT_NAME
     *
     * @mbggenerated
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.MERCHANT_NAME
     *
     * @param merchantName the value for biz_asset.MERCHANT_NAME
     *
     * @mbggenerated
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.ASSET_APPLY_TIME
     *
     * @return the value of biz_asset.ASSET_APPLY_TIME
     *
     * @mbggenerated
     */
    public Date getAssetApplyTime() {
        return assetApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.ASSET_APPLY_TIME
     *
     * @param assetApplyTime the value for biz_asset.ASSET_APPLY_TIME
     *
     * @mbggenerated
     */
    public void setAssetApplyTime(Date assetApplyTime) {
        this.assetApplyTime = assetApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.INSTALLMENT_APPLY_TIME
     *
     * @return the value of biz_asset.INSTALLMENT_APPLY_TIME
     *
     * @mbggenerated
     */
    public Date getInstallmentApplyTime() {
        return installmentApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.INSTALLMENT_APPLY_TIME
     *
     * @param installmentApplyTime the value for biz_asset.INSTALLMENT_APPLY_TIME
     *
     * @mbggenerated
     */
    public void setInstallmentApplyTime(Date installmentApplyTime) {
        this.installmentApplyTime = installmentApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.AMOUNT
     *
     * @return the value of biz_asset.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.AMOUNT
     *
     * @param amount the value for biz_asset.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.PERIOD
     *
     * @return the value of biz_asset.PERIOD
     *
     * @mbggenerated
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.PERIOD
     *
     * @param period the value for biz_asset.PERIOD
     *
     * @mbggenerated
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.PERIOD_LENGTH
     *
     * @return the value of biz_asset.PERIOD_LENGTH
     *
     * @mbggenerated
     */
    public String getPeriodLength() {
        return periodLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.PERIOD_LENGTH
     *
     * @param periodLength the value for biz_asset.PERIOD_LENGTH
     *
     * @mbggenerated
     */
    public void setPeriodLength(String periodLength) {
        this.periodLength = periodLength == null ? null : periodLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.NOTE
     *
     * @return the value of biz_asset.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.NOTE
     *
     * @param note the value for biz_asset.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.STATUS
     *
     * @return the value of biz_asset.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.STATUS
     *
     * @param status the value for biz_asset.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.CREATE_TIME
     *
     * @return the value of biz_asset.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.CREATE_TIME
     *
     * @param createTime the value for biz_asset.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.UPDATE_TIME
     *
     * @return the value of biz_asset.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.UPDATE_TIME
     *
     * @param updateTime the value for biz_asset.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.CREATOR_ID
     *
     * @return the value of biz_asset.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.CREATOR_ID
     *
     * @param creatorId the value for biz_asset.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.UPDATER_ID
     *
     * @return the value of biz_asset.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.UPDATER_ID
     *
     * @param updaterId the value for biz_asset.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.CREATOR_NAME
     *
     * @return the value of biz_asset.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.CREATOR_NAME
     *
     * @param creatorName the value for biz_asset.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset.UPDATER_NAME
     *
     * @return the value of biz_asset.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset.UPDATER_NAME
     *
     * @param updaterName the value for biz_asset.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}