package com.jufan.entity;

public class BizApplyInstallmentWithBLOBs extends BizApplyInstallment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_apply_installment.APPL_EXT
     *
     * @mbggenerated
     */
    private String applExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_apply_installment.APPLY_CONTENT
     *
     * @mbggenerated
     */
    private String applyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_apply_installment.APPL_EXT
     *
     * @return the value of biz_apply_installment.APPL_EXT
     *
     * @mbggenerated
     */
    public String getApplExt() {
        return applExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_apply_installment.APPL_EXT
     *
     * @param applExt the value for biz_apply_installment.APPL_EXT
     *
     * @mbggenerated
     */
    public void setApplExt(String applExt) {
        this.applExt = applExt == null ? null : applExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_apply_installment.APPLY_CONTENT
     *
     * @return the value of biz_apply_installment.APPLY_CONTENT
     *
     * @mbggenerated
     */
    public String getApplyContent() {
        return applyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_apply_installment.APPLY_CONTENT
     *
     * @param applyContent the value for biz_apply_installment.APPLY_CONTENT
     *
     * @mbggenerated
     */
    public void setApplyContent(String applyContent) {
        this.applyContent = applyContent == null ? null : applyContent.trim();
    }
}