package com.jufan.entity;

public class BizAssetProjectRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset_project_rel.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset_project_rel.BIZ_ASSET_ID
     *
     * @mbggenerated
     */
    private String bizAssetId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset_project_rel.BIZ_PROJECT_ID
     *
     * @mbggenerated
     */
    private String bizProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_asset_project_rel.PROJECT_TYPE
     *
     * @mbggenerated
     */
    private String projectType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset_project_rel.ID
     *
     * @return the value of biz_asset_project_rel.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset_project_rel.ID
     *
     * @param id the value for biz_asset_project_rel.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset_project_rel.BIZ_ASSET_ID
     *
     * @return the value of biz_asset_project_rel.BIZ_ASSET_ID
     *
     * @mbggenerated
     */
    public String getBizAssetId() {
        return bizAssetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset_project_rel.BIZ_ASSET_ID
     *
     * @param bizAssetId the value for biz_asset_project_rel.BIZ_ASSET_ID
     *
     * @mbggenerated
     */
    public void setBizAssetId(String bizAssetId) {
        this.bizAssetId = bizAssetId == null ? null : bizAssetId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset_project_rel.BIZ_PROJECT_ID
     *
     * @return the value of biz_asset_project_rel.BIZ_PROJECT_ID
     *
     * @mbggenerated
     */
    public String getBizProjectId() {
        return bizProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset_project_rel.BIZ_PROJECT_ID
     *
     * @param bizProjectId the value for biz_asset_project_rel.BIZ_PROJECT_ID
     *
     * @mbggenerated
     */
    public void setBizProjectId(String bizProjectId) {
        this.bizProjectId = bizProjectId == null ? null : bizProjectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_asset_project_rel.PROJECT_TYPE
     *
     * @return the value of biz_asset_project_rel.PROJECT_TYPE
     *
     * @mbggenerated
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_asset_project_rel.PROJECT_TYPE
     *
     * @param projectType the value for biz_asset_project_rel.PROJECT_TYPE
     *
     * @mbggenerated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }
}