package com.jufan.entity;

import java.util.Date;

public class BizContractOpHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CONTRACT_ID
     *
     * @mbggenerated
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CURRENT_OPERATE_TYPE
     *
     * @mbggenerated
     */
    private String currentOperateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CURRENT_OPERATE_STATUS
     *
     * @mbggenerated
     */
    private String currentOperateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CURRENT_OPERATE_APPLY_TIME
     *
     * @mbggenerated
     */
    private Date currentOperateApplyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CURRENT_OPERATE_APPROVE_TIME
     *
     * @mbggenerated
     */
    private Date currentOperateApproveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_contract_op_history.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.ID
     *
     * @return the value of biz_contract_op_history.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.ID
     *
     * @param id the value for biz_contract_op_history.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CONTRACT_ID
     *
     * @return the value of biz_contract_op_history.CONTRACT_ID
     *
     * @mbggenerated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CONTRACT_ID
     *
     * @param contractId the value for biz_contract_op_history.CONTRACT_ID
     *
     * @mbggenerated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CURRENT_OPERATE_TYPE
     *
     * @return the value of biz_contract_op_history.CURRENT_OPERATE_TYPE
     *
     * @mbggenerated
     */
    public String getCurrentOperateType() {
        return currentOperateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CURRENT_OPERATE_TYPE
     *
     * @param currentOperateType the value for biz_contract_op_history.CURRENT_OPERATE_TYPE
     *
     * @mbggenerated
     */
    public void setCurrentOperateType(String currentOperateType) {
        this.currentOperateType = currentOperateType == null ? null : currentOperateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CURRENT_OPERATE_STATUS
     *
     * @return the value of biz_contract_op_history.CURRENT_OPERATE_STATUS
     *
     * @mbggenerated
     */
    public String getCurrentOperateStatus() {
        return currentOperateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CURRENT_OPERATE_STATUS
     *
     * @param currentOperateStatus the value for biz_contract_op_history.CURRENT_OPERATE_STATUS
     *
     * @mbggenerated
     */
    public void setCurrentOperateStatus(String currentOperateStatus) {
        this.currentOperateStatus = currentOperateStatus == null ? null : currentOperateStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CURRENT_OPERATE_APPLY_TIME
     *
     * @return the value of biz_contract_op_history.CURRENT_OPERATE_APPLY_TIME
     *
     * @mbggenerated
     */
    public Date getCurrentOperateApplyTime() {
        return currentOperateApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CURRENT_OPERATE_APPLY_TIME
     *
     * @param currentOperateApplyTime the value for biz_contract_op_history.CURRENT_OPERATE_APPLY_TIME
     *
     * @mbggenerated
     */
    public void setCurrentOperateApplyTime(Date currentOperateApplyTime) {
        this.currentOperateApplyTime = currentOperateApplyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CURRENT_OPERATE_APPROVE_TIME
     *
     * @return the value of biz_contract_op_history.CURRENT_OPERATE_APPROVE_TIME
     *
     * @mbggenerated
     */
    public Date getCurrentOperateApproveTime() {
        return currentOperateApproveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CURRENT_OPERATE_APPROVE_TIME
     *
     * @param currentOperateApproveTime the value for biz_contract_op_history.CURRENT_OPERATE_APPROVE_TIME
     *
     * @mbggenerated
     */
    public void setCurrentOperateApproveTime(Date currentOperateApproveTime) {
        this.currentOperateApproveTime = currentOperateApproveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.NOTE
     *
     * @return the value of biz_contract_op_history.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.NOTE
     *
     * @param note the value for biz_contract_op_history.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.STATUS
     *
     * @return the value of biz_contract_op_history.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.STATUS
     *
     * @param status the value for biz_contract_op_history.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CREATE_TIME
     *
     * @return the value of biz_contract_op_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CREATE_TIME
     *
     * @param createTime the value for biz_contract_op_history.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.UPDATE_TIME
     *
     * @return the value of biz_contract_op_history.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.UPDATE_TIME
     *
     * @param updateTime the value for biz_contract_op_history.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CREATOR_ID
     *
     * @return the value of biz_contract_op_history.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CREATOR_ID
     *
     * @param creatorId the value for biz_contract_op_history.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.UPDATER_ID
     *
     * @return the value of biz_contract_op_history.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.UPDATER_ID
     *
     * @param updaterId the value for biz_contract_op_history.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.CREATOR_NAME
     *
     * @return the value of biz_contract_op_history.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.CREATOR_NAME
     *
     * @param creatorName the value for biz_contract_op_history.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_contract_op_history.UPDATER_NAME
     *
     * @return the value of biz_contract_op_history.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_contract_op_history.UPDATER_NAME
     *
     * @param updaterName the value for biz_contract_op_history.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}