package com.jufan.entity;

public class BizPricingModelWithBLOBs extends BizPricingModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pricing_model.RULE1
     *
     * @mbggenerated
     */
    private String rule1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pricing_model.RULE2
     *
     * @mbggenerated
     */
    private String rule2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_pricing_model.RULE3
     *
     * @mbggenerated
     */
    private String rule3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pricing_model.RULE1
     *
     * @return the value of biz_pricing_model.RULE1
     *
     * @mbggenerated
     */
    public String getRule1() {
        return rule1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pricing_model.RULE1
     *
     * @param rule1 the value for biz_pricing_model.RULE1
     *
     * @mbggenerated
     */
    public void setRule1(String rule1) {
        this.rule1 = rule1 == null ? null : rule1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pricing_model.RULE2
     *
     * @return the value of biz_pricing_model.RULE2
     *
     * @mbggenerated
     */
    public String getRule2() {
        return rule2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pricing_model.RULE2
     *
     * @param rule2 the value for biz_pricing_model.RULE2
     *
     * @mbggenerated
     */
    public void setRule2(String rule2) {
        this.rule2 = rule2 == null ? null : rule2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_pricing_model.RULE3
     *
     * @return the value of biz_pricing_model.RULE3
     *
     * @mbggenerated
     */
    public String getRule3() {
        return rule3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_pricing_model.RULE3
     *
     * @param rule3 the value for biz_pricing_model.RULE3
     *
     * @mbggenerated
     */
    public void setRule3(String rule3) {
        this.rule3 = rule3 == null ? null : rule3.trim();
    }
}