package com.jufan.entity;

public class BizProjectWithBLOBs extends BizProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.PROJECT_CONTENT
     *
     * @mbggenerated
     */
    private String projectContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.CUSTOMER_CONTENT
     *
     * @mbggenerated
     */
    private String customerContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.PROJECT_CONTENT
     *
     * @return the value of biz_project.PROJECT_CONTENT
     *
     * @mbggenerated
     */
    public String getProjectContent() {
        return projectContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.PROJECT_CONTENT
     *
     * @param projectContent the value for biz_project.PROJECT_CONTENT
     *
     * @mbggenerated
     */
    public void setProjectContent(String projectContent) {
        this.projectContent = projectContent == null ? null : projectContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.CUSTOMER_CONTENT
     *
     * @return the value of biz_project.CUSTOMER_CONTENT
     *
     * @mbggenerated
     */
    public String getCustomerContent() {
        return customerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.CUSTOMER_CONTENT
     *
     * @param customerContent the value for biz_project.CUSTOMER_CONTENT
     *
     * @mbggenerated
     */
    public void setCustomerContent(String customerContent) {
        this.customerContent = customerContent == null ? null : customerContent.trim();
    }
}