package com.jufan.entity;

import java.util.Date;

public class BizRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.RULE_NAME
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.RULE_TYPE
     *
     * @mbggenerated
     */
    private String ruleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.RULE_VALUE
     *
     * @mbggenerated
     */
    private String ruleValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.RULE_GROUP
     *
     * @mbggenerated
     */
    private String ruleGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.BIZ_TYPE
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.VALID_START_TIME
     *
     * @mbggenerated
     */
    private Date validStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_rule.VALID_END_TIME
     *
     * @mbggenerated
     */
    private Date validEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.ID
     *
     * @return the value of biz_rule.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.ID
     *
     * @param id the value for biz_rule.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.MERCHANT_ID
     *
     * @return the value of biz_rule.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.MERCHANT_ID
     *
     * @param merchantId the value for biz_rule.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.RULE_NAME
     *
     * @return the value of biz_rule.RULE_NAME
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.RULE_NAME
     *
     * @param ruleName the value for biz_rule.RULE_NAME
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.RULE_TYPE
     *
     * @return the value of biz_rule.RULE_TYPE
     *
     * @mbggenerated
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.RULE_TYPE
     *
     * @param ruleType the value for biz_rule.RULE_TYPE
     *
     * @mbggenerated
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.RULE_VALUE
     *
     * @return the value of biz_rule.RULE_VALUE
     *
     * @mbggenerated
     */
    public String getRuleValue() {
        return ruleValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.RULE_VALUE
     *
     * @param ruleValue the value for biz_rule.RULE_VALUE
     *
     * @mbggenerated
     */
    public void setRuleValue(String ruleValue) {
        this.ruleValue = ruleValue == null ? null : ruleValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.RULE_GROUP
     *
     * @return the value of biz_rule.RULE_GROUP
     *
     * @mbggenerated
     */
    public String getRuleGroup() {
        return ruleGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.RULE_GROUP
     *
     * @param ruleGroup the value for biz_rule.RULE_GROUP
     *
     * @mbggenerated
     */
    public void setRuleGroup(String ruleGroup) {
        this.ruleGroup = ruleGroup == null ? null : ruleGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.BIZ_TYPE
     *
     * @return the value of biz_rule.BIZ_TYPE
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.BIZ_TYPE
     *
     * @param bizType the value for biz_rule.BIZ_TYPE
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.NOTE
     *
     * @return the value of biz_rule.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.NOTE
     *
     * @param note the value for biz_rule.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.STATUS
     *
     * @return the value of biz_rule.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.STATUS
     *
     * @param status the value for biz_rule.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.CREATE_TIME
     *
     * @return the value of biz_rule.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.CREATE_TIME
     *
     * @param createTime the value for biz_rule.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.UPDATE_TIME
     *
     * @return the value of biz_rule.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.UPDATE_TIME
     *
     * @param updateTime the value for biz_rule.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.CREATOR_ID
     *
     * @return the value of biz_rule.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.CREATOR_ID
     *
     * @param creatorId the value for biz_rule.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.UPDATER_ID
     *
     * @return the value of biz_rule.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.UPDATER_ID
     *
     * @param updaterId the value for biz_rule.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.CREATOR_NAME
     *
     * @return the value of biz_rule.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.CREATOR_NAME
     *
     * @param creatorName the value for biz_rule.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.UPDATER_NAME
     *
     * @return the value of biz_rule.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.UPDATER_NAME
     *
     * @param updaterName the value for biz_rule.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.VALID_START_TIME
     *
     * @return the value of biz_rule.VALID_START_TIME
     *
     * @mbggenerated
     */
    public Date getValidStartTime() {
        return validStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.VALID_START_TIME
     *
     * @param validStartTime the value for biz_rule.VALID_START_TIME
     *
     * @mbggenerated
     */
    public void setValidStartTime(Date validStartTime) {
        this.validStartTime = validStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_rule.VALID_END_TIME
     *
     * @return the value of biz_rule.VALID_END_TIME
     *
     * @mbggenerated
     */
    public Date getValidEndTime() {
        return validEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_rule.VALID_END_TIME
     *
     * @param validEndTime the value for biz_rule.VALID_END_TIME
     *
     * @mbggenerated
     */
    public void setValidEndTime(Date validEndTime) {
        this.validEndTime = validEndTime;
    }
}