package com.jufan.entity;

import java.util.Date;

public class BizType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.BIZ_TYPE
     *
     * @mbggenerated
     */
    private String bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.BIZ_NAME
     *
     * @mbggenerated
     */
    private String bizName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.BIZ_GROUP
     *
     * @mbggenerated
     */
    private String bizGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.FEATURES
     *
     * @mbggenerated
     */
    private String features;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.ID
     *
     * @return the value of biz_type.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.ID
     *
     * @param id the value for biz_type.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.BIZ_TYPE
     *
     * @return the value of biz_type.BIZ_TYPE
     *
     * @mbggenerated
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.BIZ_TYPE
     *
     * @param bizType the value for biz_type.BIZ_TYPE
     *
     * @mbggenerated
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.BIZ_NAME
     *
     * @return the value of biz_type.BIZ_NAME
     *
     * @mbggenerated
     */
    public String getBizName() {
        return bizName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.BIZ_NAME
     *
     * @param bizName the value for biz_type.BIZ_NAME
     *
     * @mbggenerated
     */
    public void setBizName(String bizName) {
        this.bizName = bizName == null ? null : bizName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.BIZ_GROUP
     *
     * @return the value of biz_type.BIZ_GROUP
     *
     * @mbggenerated
     */
    public String getBizGroup() {
        return bizGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.BIZ_GROUP
     *
     * @param bizGroup the value for biz_type.BIZ_GROUP
     *
     * @mbggenerated
     */
    public void setBizGroup(String bizGroup) {
        this.bizGroup = bizGroup == null ? null : bizGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.NOTE
     *
     * @return the value of biz_type.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.NOTE
     *
     * @param note the value for biz_type.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.STATUS
     *
     * @return the value of biz_type.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.STATUS
     *
     * @param status the value for biz_type.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.FEATURES
     *
     * @return the value of biz_type.FEATURES
     *
     * @mbggenerated
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.FEATURES
     *
     * @param features the value for biz_type.FEATURES
     *
     * @mbggenerated
     */
    public void setFeatures(String features) {
        this.features = features == null ? null : features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type.CREATE_TIME
     *
     * @return the value of biz_type.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type.CREATE_TIME
     *
     * @param createTime the value for biz_type.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

	@Override
	public String toString() {
		return "BizType [id=" + id + ", bizType=" + bizType + ", bizName=" + bizName + ", bizGroup=" + bizGroup
				+ ", note=" + note + ", status=" + status + ", features=" + features + ", createTime=" + createTime
				+ "]";
	}
}