package com.jufan.entity;

import java.util.Date;

public class BizTypeCharge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.CHARGE_TYPE
     *
     * @mbggenerated
     */
    private String chargeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.CHARGE_TYPE_NAME
     *
     * @mbggenerated
     */
    private String chargeTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.CHARGE_TYPE_GROUP
     *
     * @mbggenerated
     */
    private String chargeTypeGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.FEATURES
     *
     * @mbggenerated
     */
    private String features;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_type_charge.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.ID
     *
     * @return the value of biz_type_charge.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.ID
     *
     * @param id the value for biz_type_charge.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.CHARGE_TYPE_CODE
     *
     * @return the value of biz_type_charge.CHARGE_TYPE_CODE
     *
     * @mbggenerated
     */
    public String getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.CHARGE_TYPE_CODE
     *
     * @param chargeTypeCode the value for biz_type_charge.CHARGE_TYPE_CODE
     *
     * @mbggenerated
     */
    public void setChargeType(String chargeType) {
        this.chargeType = chargeType == null ? null : chargeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.CHARGE_TYPE_NAME
     *
     * @return the value of biz_type_charge.CHARGE_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getChargeTypeName() {
        return chargeTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.CHARGE_TYPE_NAME
     *
     * @param chargeTypeName the value for biz_type_charge.CHARGE_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setChargeTypeName(String chargeTypeName) {
        this.chargeTypeName = chargeTypeName == null ? null : chargeTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.CHARGE_TYPE_GROUP
     *
     * @return the value of biz_type_charge.CHARGE_TYPE_GROUP
     *
     * @mbggenerated
     */
    public String getChargeTypeGroup() {
        return chargeTypeGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.CHARGE_TYPE_GROUP
     *
     * @param chargeTypeGroup the value for biz_type_charge.CHARGE_TYPE_GROUP
     *
     * @mbggenerated
     */
    public void setChargeTypeGroup(String chargeTypeGroup) {
        this.chargeTypeGroup = chargeTypeGroup == null ? null : chargeTypeGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.NOTE
     *
     * @return the value of biz_type_charge.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.NOTE
     *
     * @param note the value for biz_type_charge.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.FEATURES
     *
     * @return the value of biz_type_charge.FEATURES
     *
     * @mbggenerated
     */
    public String getFeatures() {
        return features;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.FEATURES
     *
     * @param features the value for biz_type_charge.FEATURES
     *
     * @mbggenerated
     */
    public void setFeatures(String features) {
        this.features = features == null ? null : features.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.STATUS
     *
     * @return the value of biz_type_charge.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.STATUS
     *
     * @param status the value for biz_type_charge.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_type_charge.CREATE_TIME
     *
     * @return the value of biz_type_charge.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_type_charge.CREATE_TIME
     *
     * @param createTime the value for biz_type_charge.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}