package com.jufan.entity;

import java.io.Serializable;
import java.util.Date;

public class CommBankBin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.BIN
     *
     * @mbggenerated
     */
    private String bin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.BANK
     *
     * @mbggenerated
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.CARD_NAME
     *
     * @mbggenerated
     */
    private String cardName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.CARD_TYPE
     *
     * @mbggenerated
     */
    private String cardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.IMAGE_ID
     *
     * @mbggenerated
     */
    private String imageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.IMAGE_MD5
     *
     * @mbggenerated
     */
    private String imageMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_bank_bin.BANK_NUMBER
     *
     * @mbggenerated
     */
    private String bankNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.ID
     *
     * @return the value of comm_bank_bin.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.ID
     *
     * @param id the value for comm_bank_bin.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.BIN
     *
     * @return the value of comm_bank_bin.BIN
     *
     * @mbggenerated
     */
    public String getBin() {
        return bin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.BIN
     *
     * @param bin the value for comm_bank_bin.BIN
     *
     * @mbggenerated
     */
    public void setBin(String bin) {
        this.bin = bin == null ? null : bin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.BANK
     *
     * @return the value of comm_bank_bin.BANK
     *
     * @mbggenerated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.BANK
     *
     * @param bank the value for comm_bank_bin.BANK
     *
     * @mbggenerated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.BANK_CODE
     *
     * @return the value of comm_bank_bin.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.BANK_CODE
     *
     * @param bankCode the value for comm_bank_bin.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.CARD_NAME
     *
     * @return the value of comm_bank_bin.CARD_NAME
     *
     * @mbggenerated
     */
    public String getCardName() {
        return cardName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.CARD_NAME
     *
     * @param cardName the value for comm_bank_bin.CARD_NAME
     *
     * @mbggenerated
     */
    public void setCardName(String cardName) {
        this.cardName = cardName == null ? null : cardName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.CARD_TYPE
     *
     * @return the value of comm_bank_bin.CARD_TYPE
     *
     * @mbggenerated
     */
    public String getCardType() {
        return cardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.CARD_TYPE
     *
     * @param cardType the value for comm_bank_bin.CARD_TYPE
     *
     * @mbggenerated
     */
    public void setCardType(String cardType) {
        this.cardType = cardType == null ? null : cardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.IMAGE_ID
     *
     * @return the value of comm_bank_bin.IMAGE_ID
     *
     * @mbggenerated
     */
    public String getImageId() {
        return imageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.IMAGE_ID
     *
     * @param imageId the value for comm_bank_bin.IMAGE_ID
     *
     * @mbggenerated
     */
    public void setImageId(String imageId) {
        this.imageId = imageId == null ? null : imageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.IMAGE_MD5
     *
     * @return the value of comm_bank_bin.IMAGE_MD5
     *
     * @mbggenerated
     */
    public String getImageMd5() {
        return imageMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.IMAGE_MD5
     *
     * @param imageMd5 the value for comm_bank_bin.IMAGE_MD5
     *
     * @mbggenerated
     */
    public void setImageMd5(String imageMd5) {
        this.imageMd5 = imageMd5 == null ? null : imageMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.UPDATE_TIME
     *
     * @return the value of comm_bank_bin.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.UPDATE_TIME
     *
     * @param updateTime the value for comm_bank_bin.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_bank_bin.BANK_NUMBER
     *
     * @return the value of comm_bank_bin.BANK_NUMBER
     *
     * @mbggenerated
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_bank_bin.BANK_NUMBER
     *
     * @param bankNumber the value for comm_bank_bin.BANK_NUMBER
     *
     * @mbggenerated
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber == null ? null : bankNumber.trim();
    }
}