package com.jufan.entity;

public class CommArea {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.PARENT_ID
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.SHORT_NAME
     *
     * @mbggenerated
     */
    private String shortName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.LEVEL_TYPE
     *
     * @mbggenerated
     */
    private Integer levelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.ZIP_CODE
     *
     * @mbggenerated
     */
    private String zipCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.MERGER_NAME
     *
     * @mbggenerated
     */
    private String mergerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.LNG
     *
     * @mbggenerated
     */
    private String lng;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.LAT
     *
     * @mbggenerated
     */
    private String lat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_area.PINYIN
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.ID
     *
     * @return the value of comm_area.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.ID
     *
     * @param id the value for comm_area.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.NAME
     *
     * @return the value of comm_area.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.NAME
     *
     * @param name the value for comm_area.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.PARENT_ID
     *
     * @return the value of comm_area.PARENT_ID
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.PARENT_ID
     *
     * @param parentId the value for comm_area.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.SHORT_NAME
     *
     * @return the value of comm_area.SHORT_NAME
     *
     * @mbggenerated
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.SHORT_NAME
     *
     * @param shortName the value for comm_area.SHORT_NAME
     *
     * @mbggenerated
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.LEVEL_TYPE
     *
     * @return the value of comm_area.LEVEL_TYPE
     *
     * @mbggenerated
     */
    public Integer getLevelType() {
        return levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.LEVEL_TYPE
     *
     * @param levelType the value for comm_area.LEVEL_TYPE
     *
     * @mbggenerated
     */
    public void setLevelType(Integer levelType) {
        this.levelType = levelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.CITY_CODE
     *
     * @return the value of comm_area.CITY_CODE
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.CITY_CODE
     *
     * @param cityCode the value for comm_area.CITY_CODE
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.ZIP_CODE
     *
     * @return the value of comm_area.ZIP_CODE
     *
     * @mbggenerated
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.ZIP_CODE
     *
     * @param zipCode the value for comm_area.ZIP_CODE
     *
     * @mbggenerated
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.MERGER_NAME
     *
     * @return the value of comm_area.MERGER_NAME
     *
     * @mbggenerated
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.MERGER_NAME
     *
     * @param mergerName the value for comm_area.MERGER_NAME
     *
     * @mbggenerated
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.LNG
     *
     * @return the value of comm_area.LNG
     *
     * @mbggenerated
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.LNG
     *
     * @param lng the value for comm_area.LNG
     *
     * @mbggenerated
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.LAT
     *
     * @return the value of comm_area.LAT
     *
     * @mbggenerated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.LAT
     *
     * @param lat the value for comm_area.LAT
     *
     * @mbggenerated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_area.PINYIN
     *
     * @return the value of comm_area.PINYIN
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_area.PINYIN
     *
     * @param pinyin the value for comm_area.PINYIN
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}