package com.jufan.entity;

import java.util.Date;

public class CommOperationLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.LEVEL
     *
     * @mbggenerated
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.SERVER_ID
     *
     * @mbggenerated
     */
    private String serverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.CLIENT_ID
     *
     * @mbggenerated
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.OPERATE_TIME
     *
     * @mbggenerated
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    private String operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.OPERATOR_NAME
     *
     * @mbggenerated
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_operation_log.MESSAGE
     *
     * @mbggenerated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.ID
     *
     * @return the value of comm_operation_log.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.ID
     *
     * @param id the value for comm_operation_log.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.LEVEL
     *
     * @return the value of comm_operation_log.LEVEL
     *
     * @mbggenerated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.LEVEL
     *
     * @param level the value for comm_operation_log.LEVEL
     *
     * @mbggenerated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.NAME
     *
     * @return the value of comm_operation_log.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.NAME
     *
     * @param name the value for comm_operation_log.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.SERVER_ID
     *
     * @return the value of comm_operation_log.SERVER_ID
     *
     * @mbggenerated
     */
    public String getServerId() {
        return serverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.SERVER_ID
     *
     * @param serverId the value for comm_operation_log.SERVER_ID
     *
     * @mbggenerated
     */
    public void setServerId(String serverId) {
        this.serverId = serverId == null ? null : serverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.CLIENT_ID
     *
     * @return the value of comm_operation_log.CLIENT_ID
     *
     * @mbggenerated
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.CLIENT_ID
     *
     * @param clientId the value for comm_operation_log.CLIENT_ID
     *
     * @mbggenerated
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.OPERATE_TIME
     *
     * @return the value of comm_operation_log.OPERATE_TIME
     *
     * @mbggenerated
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.OPERATE_TIME
     *
     * @param operateTime the value for comm_operation_log.OPERATE_TIME
     *
     * @mbggenerated
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.OPERATOR_ID
     *
     * @return the value of comm_operation_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.OPERATOR_ID
     *
     * @param operatorId the value for comm_operation_log.OPERATOR_ID
     *
     * @mbggenerated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.OPERATOR_NAME
     *
     * @return the value of comm_operation_log.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.OPERATOR_NAME
     *
     * @param operatorName the value for comm_operation_log.OPERATOR_NAME
     *
     * @mbggenerated
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.STATUS
     *
     * @return the value of comm_operation_log.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.STATUS
     *
     * @param status the value for comm_operation_log.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_operation_log.MESSAGE
     *
     * @return the value of comm_operation_log.MESSAGE
     *
     * @mbggenerated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_operation_log.MESSAGE
     *
     * @param message the value for comm_operation_log.MESSAGE
     *
     * @mbggenerated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}