package com.jufan.entity;

import java.util.Date;

public class CommFileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.APP_ID
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.REF_TYPE
     *
     * @mbggenerated
     */
    private String refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.REF_ID
     *
     * @mbggenerated
     */
    private String refId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.KEYWORD
     *
     * @mbggenerated
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.FILE_ORIGIN_NAME
     *
     * @mbggenerated
     */
    private String fileOriginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.FILE_SIZE
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.FILE_TYPE
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.CHECKSUM
     *
     * @mbggenerated
     */
    private String checksum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_file_info.VERSION
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.ID
     *
     * @return the value of comm_file_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.ID
     *
     * @param id the value for comm_file_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.APP_ID
     *
     * @return the value of comm_file_info.APP_ID
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.APP_ID
     *
     * @param appId the value for comm_file_info.APP_ID
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.REF_TYPE
     *
     * @return the value of comm_file_info.REF_TYPE
     *
     * @mbggenerated
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.REF_TYPE
     *
     * @param refType the value for comm_file_info.REF_TYPE
     *
     * @mbggenerated
     */
    public void setRefType(String refType) {
        this.refType = refType == null ? null : refType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.REF_ID
     *
     * @return the value of comm_file_info.REF_ID
     *
     * @mbggenerated
     */
    public String getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.REF_ID
     *
     * @param refId the value for comm_file_info.REF_ID
     *
     * @mbggenerated
     */
    public void setRefId(String refId) {
        this.refId = refId == null ? null : refId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.KEYWORD
     *
     * @return the value of comm_file_info.KEYWORD
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.KEYWORD
     *
     * @param keyword the value for comm_file_info.KEYWORD
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.FILE_NAME
     *
     * @return the value of comm_file_info.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.FILE_NAME
     *
     * @param fileName the value for comm_file_info.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.FILE_ORIGIN_NAME
     *
     * @return the value of comm_file_info.FILE_ORIGIN_NAME
     *
     * @mbggenerated
     */
    public String getFileOriginName() {
        return fileOriginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.FILE_ORIGIN_NAME
     *
     * @param fileOriginName the value for comm_file_info.FILE_ORIGIN_NAME
     *
     * @mbggenerated
     */
    public void setFileOriginName(String fileOriginName) {
        this.fileOriginName = fileOriginName == null ? null : fileOriginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.FILE_SIZE
     *
     * @return the value of comm_file_info.FILE_SIZE
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.FILE_SIZE
     *
     * @param fileSize the value for comm_file_info.FILE_SIZE
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.FILE_TYPE
     *
     * @return the value of comm_file_info.FILE_TYPE
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.FILE_TYPE
     *
     * @param fileType the value for comm_file_info.FILE_TYPE
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.DESCRIPTION
     *
     * @return the value of comm_file_info.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.DESCRIPTION
     *
     * @param description the value for comm_file_info.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.URL
     *
     * @return the value of comm_file_info.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.URL
     *
     * @param url the value for comm_file_info.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.CHECKSUM
     *
     * @return the value of comm_file_info.CHECKSUM
     *
     * @mbggenerated
     */
    public String getChecksum() {
        return checksum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.CHECKSUM
     *
     * @param checksum the value for comm_file_info.CHECKSUM
     *
     * @mbggenerated
     */
    public void setChecksum(String checksum) {
        this.checksum = checksum == null ? null : checksum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.STATUS
     *
     * @return the value of comm_file_info.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.STATUS
     *
     * @param status the value for comm_file_info.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.CREATE_TIME
     *
     * @return the value of comm_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.CREATE_TIME
     *
     * @param createTime the value for comm_file_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.UPDATE_TIME
     *
     * @return the value of comm_file_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.UPDATE_TIME
     *
     * @param updateTime the value for comm_file_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.CREATOR_ID
     *
     * @return the value of comm_file_info.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.CREATOR_ID
     *
     * @param creatorId the value for comm_file_info.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.UPDATER_ID
     *
     * @return the value of comm_file_info.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.UPDATER_ID
     *
     * @param updaterId the value for comm_file_info.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.CREATOR_NAME
     *
     * @return the value of comm_file_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.CREATOR_NAME
     *
     * @param creatorName the value for comm_file_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.UPDATER_NAME
     *
     * @return the value of comm_file_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.UPDATER_NAME
     *
     * @param updaterName the value for comm_file_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_file_info.VERSION
     *
     * @return the value of comm_file_info.VERSION
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_file_info.VERSION
     *
     * @param version the value for comm_file_info.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}