package com.jufan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ExtApplyInstallmentInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPLY_ID
     *
     * @mbggenerated
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPROVE_NOTES
     *
     * @mbggenerated
     */
    private String approveNotes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPL_HUKOU_APCR_NAMES
     *
     * @mbggenerated
     */
    private String applHukouApcrNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPL_HUKOU_ADDRESS
     *
     * @mbggenerated
     */
    private String applHukouAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.SPOUSE_NAME
     *
     * @mbggenerated
     */
    private String spouseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.SPOUSE_CERT_NUMBER
     *
     * @mbggenerated
     */
    private String spouseCertNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.SPOUSE_MOBILE
     *
     * @mbggenerated
     */
    private String spouseMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPL_HOUSE_TYPE
     *
     * @mbggenerated
     */
    private String applHouseType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPL_EXPERIENCE
     *
     * @mbggenerated
     */
    private BigDecimal applExperience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.APPL_NATION
     *
     * @mbggenerated
     */
    private String applNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CA_SIGN_STATUS
     *
     * @mbggenerated
     */
    private String caSignStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CA_SIGN_TIME
     *
     * @mbggenerated
     */
    private Date caSignTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_COMPANY_NAME
     *
     * @mbggenerated
     */
    private String workExpCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_POSITION
     *
     * @mbggenerated
     */
    private String workExpPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_CPCR_CODES
     *
     * @mbggenerated
     */
    private String workExpCpcrCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_CPCR_NAMES
     *
     * @mbggenerated
     */
    private String workExpCpcrNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    private String workExpCompanyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_COMPANY_TEL
     *
     * @mbggenerated
     */
    private String workExpCompanyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_INCOME
     *
     * @mbggenerated
     */
    private BigDecimal workExpIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_INDUSTRY
     *
     * @mbggenerated
     */
    private String workExpIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_ENTNATURE
     *
     * @mbggenerated
     */
    private String workExpEntnature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_DEPARTMENT
     *
     * @mbggenerated
     */
    private String workExpDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_QUARETERS
     *
     * @mbggenerated
     */
    private String workExpQuareters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_WORKTIME
     *
     * @mbggenerated
     */
    private String workExpWorktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_EXP_RANK
     *
     * @mbggenerated
     */
    private String workExpRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.EDU_INF_LEVEL
     *
     * @mbggenerated
     */
    private String eduInfLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.EDU_INF_SCHOOL
     *
     * @mbggenerated
     */
    private String eduInfSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.EDU_INF_DEPARTMENT
     *
     * @mbggenerated
     */
    private String eduInfDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.EDU_INF_ATTENDANCE_DATE
     *
     * @mbggenerated
     */
    private String eduInfAttendanceDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.RI_FACE_RESULT
     *
     * @mbggenerated
     */
    private String riFaceResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.RI_CHOOL_VALIDATE
     *
     * @mbggenerated
     */
    private String riChoolValidate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.RI_ZHIMA_SCORE
     *
     * @mbggenerated
     */
    private String riZhimaScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.RI_VEHICLE_VALID
     *
     * @mbggenerated
     */
    private String riVehicleValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.WORK_STATUS
     *
     * @mbggenerated
     */
    private String workStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.INCOME_SOURCE
     *
     * @mbggenerated
     */
    private String incomeSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CHANNEL_CODE
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.USE_TYPE
     *
     * @mbggenerated
     */
    private String useType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.PURPOSE
     *
     * @mbggenerated
     */
    private String purpose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CONTRACT_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal contractPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.MERCHANT_PROPOSE_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal merchantProposeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.MERCHANT_PROPOSE_PERIOD
     *
     * @mbggenerated
     */
    private Integer merchantProposePeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.MERCHANT_INQUIRE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal merchantInquirePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.HAS_STORE_NUM
     *
     * @mbggenerated
     */
    private Integer hasStoreNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_apply_installment_inf.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.ID
     *
     * @return the value of ext_apply_installment_inf.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.ID
     *
     * @param id the value for ext_apply_installment_inf.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPLY_ID
     *
     * @return the value of ext_apply_installment_inf.APPLY_ID
     *
     * @mbggenerated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPLY_ID
     *
     * @param applyId the value for ext_apply_installment_inf.APPLY_ID
     *
     * @mbggenerated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPROVE_NOTES
     *
     * @return the value of ext_apply_installment_inf.APPROVE_NOTES
     *
     * @mbggenerated
     */
    public String getApproveNotes() {
        return approveNotes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPROVE_NOTES
     *
     * @param approveNotes the value for ext_apply_installment_inf.APPROVE_NOTES
     *
     * @mbggenerated
     */
    public void setApproveNotes(String approveNotes) {
        this.approveNotes = approveNotes == null ? null : approveNotes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPL_HUKOU_APCR_NAMES
     *
     * @return the value of ext_apply_installment_inf.APPL_HUKOU_APCR_NAMES
     *
     * @mbggenerated
     */
    public String getApplHukouApcrNames() {
        return applHukouApcrNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPL_HUKOU_APCR_NAMES
     *
     * @param applHukouApcrNames the value for ext_apply_installment_inf.APPL_HUKOU_APCR_NAMES
     *
     * @mbggenerated
     */
    public void setApplHukouApcrNames(String applHukouApcrNames) {
        this.applHukouApcrNames = applHukouApcrNames == null ? null : applHukouApcrNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPL_HUKOU_ADDRESS
     *
     * @return the value of ext_apply_installment_inf.APPL_HUKOU_ADDRESS
     *
     * @mbggenerated
     */
    public String getApplHukouAddress() {
        return applHukouAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPL_HUKOU_ADDRESS
     *
     * @param applHukouAddress the value for ext_apply_installment_inf.APPL_HUKOU_ADDRESS
     *
     * @mbggenerated
     */
    public void setApplHukouAddress(String applHukouAddress) {
        this.applHukouAddress = applHukouAddress == null ? null : applHukouAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.SPOUSE_NAME
     *
     * @return the value of ext_apply_installment_inf.SPOUSE_NAME
     *
     * @mbggenerated
     */
    public String getSpouseName() {
        return spouseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.SPOUSE_NAME
     *
     * @param spouseName the value for ext_apply_installment_inf.SPOUSE_NAME
     *
     * @mbggenerated
     */
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName == null ? null : spouseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.SPOUSE_CERT_NUMBER
     *
     * @return the value of ext_apply_installment_inf.SPOUSE_CERT_NUMBER
     *
     * @mbggenerated
     */
    public String getSpouseCertNumber() {
        return spouseCertNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.SPOUSE_CERT_NUMBER
     *
     * @param spouseCertNumber the value for ext_apply_installment_inf.SPOUSE_CERT_NUMBER
     *
     * @mbggenerated
     */
    public void setSpouseCertNumber(String spouseCertNumber) {
        this.spouseCertNumber = spouseCertNumber == null ? null : spouseCertNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.SPOUSE_MOBILE
     *
     * @return the value of ext_apply_installment_inf.SPOUSE_MOBILE
     *
     * @mbggenerated
     */
    public String getSpouseMobile() {
        return spouseMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.SPOUSE_MOBILE
     *
     * @param spouseMobile the value for ext_apply_installment_inf.SPOUSE_MOBILE
     *
     * @mbggenerated
     */
    public void setSpouseMobile(String spouseMobile) {
        this.spouseMobile = spouseMobile == null ? null : spouseMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPL_HOUSE_TYPE
     *
     * @return the value of ext_apply_installment_inf.APPL_HOUSE_TYPE
     *
     * @mbggenerated
     */
    public String getApplHouseType() {
        return applHouseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPL_HOUSE_TYPE
     *
     * @param applHouseType the value for ext_apply_installment_inf.APPL_HOUSE_TYPE
     *
     * @mbggenerated
     */
    public void setApplHouseType(String applHouseType) {
        this.applHouseType = applHouseType == null ? null : applHouseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPL_EXPERIENCE
     *
     * @return the value of ext_apply_installment_inf.APPL_EXPERIENCE
     *
     * @mbggenerated
     */
    public BigDecimal getApplExperience() {
        return applExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPL_EXPERIENCE
     *
     * @param applExperience the value for ext_apply_installment_inf.APPL_EXPERIENCE
     *
     * @mbggenerated
     */
    public void setApplExperience(BigDecimal applExperience) {
        this.applExperience = applExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.APPL_NATION
     *
     * @return the value of ext_apply_installment_inf.APPL_NATION
     *
     * @mbggenerated
     */
    public String getApplNation() {
        return applNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.APPL_NATION
     *
     * @param applNation the value for ext_apply_installment_inf.APPL_NATION
     *
     * @mbggenerated
     */
    public void setApplNation(String applNation) {
        this.applNation = applNation == null ? null : applNation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CA_SIGN_STATUS
     *
     * @return the value of ext_apply_installment_inf.CA_SIGN_STATUS
     *
     * @mbggenerated
     */
    public String getCaSignStatus() {
        return caSignStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CA_SIGN_STATUS
     *
     * @param caSignStatus the value for ext_apply_installment_inf.CA_SIGN_STATUS
     *
     * @mbggenerated
     */
    public void setCaSignStatus(String caSignStatus) {
        this.caSignStatus = caSignStatus == null ? null : caSignStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CA_SIGN_TIME
     *
     * @return the value of ext_apply_installment_inf.CA_SIGN_TIME
     *
     * @mbggenerated
     */
    public Date getCaSignTime() {
        return caSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CA_SIGN_TIME
     *
     * @param caSignTime the value for ext_apply_installment_inf.CA_SIGN_TIME
     *
     * @mbggenerated
     */
    public void setCaSignTime(Date caSignTime) {
        this.caSignTime = caSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_NAME
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_COMPANY_NAME
     *
     * @mbggenerated
     */
    public String getWorkExpCompanyName() {
        return workExpCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_NAME
     *
     * @param workExpCompanyName the value for ext_apply_installment_inf.WORK_EXP_COMPANY_NAME
     *
     * @mbggenerated
     */
    public void setWorkExpCompanyName(String workExpCompanyName) {
        this.workExpCompanyName = workExpCompanyName == null ? null : workExpCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_POSITION
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_POSITION
     *
     * @mbggenerated
     */
    public String getWorkExpPosition() {
        return workExpPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_POSITION
     *
     * @param workExpPosition the value for ext_apply_installment_inf.WORK_EXP_POSITION
     *
     * @mbggenerated
     */
    public void setWorkExpPosition(String workExpPosition) {
        this.workExpPosition = workExpPosition == null ? null : workExpPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_CPCR_CODES
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_CPCR_CODES
     *
     * @mbggenerated
     */
    public String getWorkExpCpcrCodes() {
        return workExpCpcrCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_CPCR_CODES
     *
     * @param workExpCpcrCodes the value for ext_apply_installment_inf.WORK_EXP_CPCR_CODES
     *
     * @mbggenerated
     */
    public void setWorkExpCpcrCodes(String workExpCpcrCodes) {
        this.workExpCpcrCodes = workExpCpcrCodes == null ? null : workExpCpcrCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_CPCR_NAMES
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_CPCR_NAMES
     *
     * @mbggenerated
     */
    public String getWorkExpCpcrNames() {
        return workExpCpcrNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_CPCR_NAMES
     *
     * @param workExpCpcrNames the value for ext_apply_installment_inf.WORK_EXP_CPCR_NAMES
     *
     * @mbggenerated
     */
    public void setWorkExpCpcrNames(String workExpCpcrNames) {
        this.workExpCpcrNames = workExpCpcrNames == null ? null : workExpCpcrNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_ADDRESS
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    public String getWorkExpCompanyAddress() {
        return workExpCompanyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_ADDRESS
     *
     * @param workExpCompanyAddress the value for ext_apply_installment_inf.WORK_EXP_COMPANY_ADDRESS
     *
     * @mbggenerated
     */
    public void setWorkExpCompanyAddress(String workExpCompanyAddress) {
        this.workExpCompanyAddress = workExpCompanyAddress == null ? null : workExpCompanyAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_TEL
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_COMPANY_TEL
     *
     * @mbggenerated
     */
    public String getWorkExpCompanyTel() {
        return workExpCompanyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_COMPANY_TEL
     *
     * @param workExpCompanyTel the value for ext_apply_installment_inf.WORK_EXP_COMPANY_TEL
     *
     * @mbggenerated
     */
    public void setWorkExpCompanyTel(String workExpCompanyTel) {
        this.workExpCompanyTel = workExpCompanyTel == null ? null : workExpCompanyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_INCOME
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_INCOME
     *
     * @mbggenerated
     */
    public BigDecimal getWorkExpIncome() {
        return workExpIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_INCOME
     *
     * @param workExpIncome the value for ext_apply_installment_inf.WORK_EXP_INCOME
     *
     * @mbggenerated
     */
    public void setWorkExpIncome(BigDecimal workExpIncome) {
        this.workExpIncome = workExpIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_INDUSTRY
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_INDUSTRY
     *
     * @mbggenerated
     */
    public String getWorkExpIndustry() {
        return workExpIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_INDUSTRY
     *
     * @param workExpIndustry the value for ext_apply_installment_inf.WORK_EXP_INDUSTRY
     *
     * @mbggenerated
     */
    public void setWorkExpIndustry(String workExpIndustry) {
        this.workExpIndustry = workExpIndustry == null ? null : workExpIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_ENTNATURE
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_ENTNATURE
     *
     * @mbggenerated
     */
    public String getWorkExpEntnature() {
        return workExpEntnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_ENTNATURE
     *
     * @param workExpEntnature the value for ext_apply_installment_inf.WORK_EXP_ENTNATURE
     *
     * @mbggenerated
     */
    public void setWorkExpEntnature(String workExpEntnature) {
        this.workExpEntnature = workExpEntnature == null ? null : workExpEntnature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_DEPARTMENT
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_DEPARTMENT
     *
     * @mbggenerated
     */
    public String getWorkExpDepartment() {
        return workExpDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_DEPARTMENT
     *
     * @param workExpDepartment the value for ext_apply_installment_inf.WORK_EXP_DEPARTMENT
     *
     * @mbggenerated
     */
    public void setWorkExpDepartment(String workExpDepartment) {
        this.workExpDepartment = workExpDepartment == null ? null : workExpDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_QUARETERS
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_QUARETERS
     *
     * @mbggenerated
     */
    public String getWorkExpQuareters() {
        return workExpQuareters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_QUARETERS
     *
     * @param workExpQuareters the value for ext_apply_installment_inf.WORK_EXP_QUARETERS
     *
     * @mbggenerated
     */
    public void setWorkExpQuareters(String workExpQuareters) {
        this.workExpQuareters = workExpQuareters == null ? null : workExpQuareters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_WORKTIME
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_WORKTIME
     *
     * @mbggenerated
     */
    public String getWorkExpWorktime() {
        return workExpWorktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_WORKTIME
     *
     * @param workExpWorktime the value for ext_apply_installment_inf.WORK_EXP_WORKTIME
     *
     * @mbggenerated
     */
    public void setWorkExpWorktime(String workExpWorktime) {
        this.workExpWorktime = workExpWorktime == null ? null : workExpWorktime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_EXP_RANK
     *
     * @return the value of ext_apply_installment_inf.WORK_EXP_RANK
     *
     * @mbggenerated
     */
    public String getWorkExpRank() {
        return workExpRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_EXP_RANK
     *
     * @param workExpRank the value for ext_apply_installment_inf.WORK_EXP_RANK
     *
     * @mbggenerated
     */
    public void setWorkExpRank(String workExpRank) {
        this.workExpRank = workExpRank == null ? null : workExpRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.EDU_INF_LEVEL
     *
     * @return the value of ext_apply_installment_inf.EDU_INF_LEVEL
     *
     * @mbggenerated
     */
    public String getEduInfLevel() {
        return eduInfLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.EDU_INF_LEVEL
     *
     * @param eduInfLevel the value for ext_apply_installment_inf.EDU_INF_LEVEL
     *
     * @mbggenerated
     */
    public void setEduInfLevel(String eduInfLevel) {
        this.eduInfLevel = eduInfLevel == null ? null : eduInfLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.EDU_INF_SCHOOL
     *
     * @return the value of ext_apply_installment_inf.EDU_INF_SCHOOL
     *
     * @mbggenerated
     */
    public String getEduInfSchool() {
        return eduInfSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.EDU_INF_SCHOOL
     *
     * @param eduInfSchool the value for ext_apply_installment_inf.EDU_INF_SCHOOL
     *
     * @mbggenerated
     */
    public void setEduInfSchool(String eduInfSchool) {
        this.eduInfSchool = eduInfSchool == null ? null : eduInfSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.EDU_INF_DEPARTMENT
     *
     * @return the value of ext_apply_installment_inf.EDU_INF_DEPARTMENT
     *
     * @mbggenerated
     */
    public String getEduInfDepartment() {
        return eduInfDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.EDU_INF_DEPARTMENT
     *
     * @param eduInfDepartment the value for ext_apply_installment_inf.EDU_INF_DEPARTMENT
     *
     * @mbggenerated
     */
    public void setEduInfDepartment(String eduInfDepartment) {
        this.eduInfDepartment = eduInfDepartment == null ? null : eduInfDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.EDU_INF_ATTENDANCE_DATE
     *
     * @return the value of ext_apply_installment_inf.EDU_INF_ATTENDANCE_DATE
     *
     * @mbggenerated
     */
    public String getEduInfAttendanceDate() {
        return eduInfAttendanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.EDU_INF_ATTENDANCE_DATE
     *
     * @param eduInfAttendanceDate the value for ext_apply_installment_inf.EDU_INF_ATTENDANCE_DATE
     *
     * @mbggenerated
     */
    public void setEduInfAttendanceDate(String eduInfAttendanceDate) {
        this.eduInfAttendanceDate = eduInfAttendanceDate == null ? null : eduInfAttendanceDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.RI_FACE_RESULT
     *
     * @return the value of ext_apply_installment_inf.RI_FACE_RESULT
     *
     * @mbggenerated
     */
    public String getRiFaceResult() {
        return riFaceResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.RI_FACE_RESULT
     *
     * @param riFaceResult the value for ext_apply_installment_inf.RI_FACE_RESULT
     *
     * @mbggenerated
     */
    public void setRiFaceResult(String riFaceResult) {
        this.riFaceResult = riFaceResult == null ? null : riFaceResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.RI_CHOOL_VALIDATE
     *
     * @return the value of ext_apply_installment_inf.RI_CHOOL_VALIDATE
     *
     * @mbggenerated
     */
    public String getRiChoolValidate() {
        return riChoolValidate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.RI_CHOOL_VALIDATE
     *
     * @param riChoolValidate the value for ext_apply_installment_inf.RI_CHOOL_VALIDATE
     *
     * @mbggenerated
     */
    public void setRiChoolValidate(String riChoolValidate) {
        this.riChoolValidate = riChoolValidate == null ? null : riChoolValidate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.RI_ZHIMA_SCORE
     *
     * @return the value of ext_apply_installment_inf.RI_ZHIMA_SCORE
     *
     * @mbggenerated
     */
    public String getRiZhimaScore() {
        return riZhimaScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.RI_ZHIMA_SCORE
     *
     * @param riZhimaScore the value for ext_apply_installment_inf.RI_ZHIMA_SCORE
     *
     * @mbggenerated
     */
    public void setRiZhimaScore(String riZhimaScore) {
        this.riZhimaScore = riZhimaScore == null ? null : riZhimaScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.RI_VEHICLE_VALID
     *
     * @return the value of ext_apply_installment_inf.RI_VEHICLE_VALID
     *
     * @mbggenerated
     */
    public String getRiVehicleValid() {
        return riVehicleValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.RI_VEHICLE_VALID
     *
     * @param riVehicleValid the value for ext_apply_installment_inf.RI_VEHICLE_VALID
     *
     * @mbggenerated
     */
    public void setRiVehicleValid(String riVehicleValid) {
        this.riVehicleValid = riVehicleValid == null ? null : riVehicleValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.WORK_STATUS
     *
     * @return the value of ext_apply_installment_inf.WORK_STATUS
     *
     * @mbggenerated
     */
    public String getWorkStatus() {
        return workStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.WORK_STATUS
     *
     * @param workStatus the value for ext_apply_installment_inf.WORK_STATUS
     *
     * @mbggenerated
     */
    public void setWorkStatus(String workStatus) {
        this.workStatus = workStatus == null ? null : workStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.INCOME_SOURCE
     *
     * @return the value of ext_apply_installment_inf.INCOME_SOURCE
     *
     * @mbggenerated
     */
    public String getIncomeSource() {
        return incomeSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.INCOME_SOURCE
     *
     * @param incomeSource the value for ext_apply_installment_inf.INCOME_SOURCE
     *
     * @mbggenerated
     */
    public void setIncomeSource(String incomeSource) {
        this.incomeSource = incomeSource == null ? null : incomeSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CHANNEL_CODE
     *
     * @return the value of ext_apply_installment_inf.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CHANNEL_CODE
     *
     * @param channelCode the value for ext_apply_installment_inf.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.USE_TYPE
     *
     * @return the value of ext_apply_installment_inf.USE_TYPE
     *
     * @mbggenerated
     */
    public String getUseType() {
        return useType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.USE_TYPE
     *
     * @param useType the value for ext_apply_installment_inf.USE_TYPE
     *
     * @mbggenerated
     */
    public void setUseType(String useType) {
        this.useType = useType == null ? null : useType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.PURPOSE
     *
     * @return the value of ext_apply_installment_inf.PURPOSE
     *
     * @mbggenerated
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.PURPOSE
     *
     * @param purpose the value for ext_apply_installment_inf.PURPOSE
     *
     * @mbggenerated
     */
    public void setPurpose(String purpose) {
        this.purpose = purpose == null ? null : purpose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CONTRACT_PRICE
     *
     * @return the value of ext_apply_installment_inf.CONTRACT_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getContractPrice() {
        return contractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CONTRACT_PRICE
     *
     * @param contractPrice the value for ext_apply_installment_inf.CONTRACT_PRICE
     *
     * @mbggenerated
     */
    public void setContractPrice(BigDecimal contractPrice) {
        this.contractPrice = contractPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.MERCHANT_PROPOSE_AMOUNT
     *
     * @return the value of ext_apply_installment_inf.MERCHANT_PROPOSE_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getMerchantProposeAmount() {
        return merchantProposeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.MERCHANT_PROPOSE_AMOUNT
     *
     * @param merchantProposeAmount the value for ext_apply_installment_inf.MERCHANT_PROPOSE_AMOUNT
     *
     * @mbggenerated
     */
    public void setMerchantProposeAmount(BigDecimal merchantProposeAmount) {
        this.merchantProposeAmount = merchantProposeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.MERCHANT_PROPOSE_PERIOD
     *
     * @return the value of ext_apply_installment_inf.MERCHANT_PROPOSE_PERIOD
     *
     * @mbggenerated
     */
    public Integer getMerchantProposePeriod() {
        return merchantProposePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.MERCHANT_PROPOSE_PERIOD
     *
     * @param merchantProposePeriod the value for ext_apply_installment_inf.MERCHANT_PROPOSE_PERIOD
     *
     * @mbggenerated
     */
    public void setMerchantProposePeriod(Integer merchantProposePeriod) {
        this.merchantProposePeriod = merchantProposePeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.MERCHANT_INQUIRE_PRICE
     *
     * @return the value of ext_apply_installment_inf.MERCHANT_INQUIRE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getMerchantInquirePrice() {
        return merchantInquirePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.MERCHANT_INQUIRE_PRICE
     *
     * @param merchantInquirePrice the value for ext_apply_installment_inf.MERCHANT_INQUIRE_PRICE
     *
     * @mbggenerated
     */
    public void setMerchantInquirePrice(BigDecimal merchantInquirePrice) {
        this.merchantInquirePrice = merchantInquirePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.HAS_STORE_NUM
     *
     * @return the value of ext_apply_installment_inf.HAS_STORE_NUM
     *
     * @mbggenerated
     */
    public Integer getHasStoreNum() {
        return hasStoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.HAS_STORE_NUM
     *
     * @param hasStoreNum the value for ext_apply_installment_inf.HAS_STORE_NUM
     *
     * @mbggenerated
     */
    public void setHasStoreNum(Integer hasStoreNum) {
        this.hasStoreNum = hasStoreNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.STATUS
     *
     * @return the value of ext_apply_installment_inf.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.STATUS
     *
     * @param status the value for ext_apply_installment_inf.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CREATE_TIME
     *
     * @return the value of ext_apply_installment_inf.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CREATE_TIME
     *
     * @param createTime the value for ext_apply_installment_inf.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.UPDATE_TIME
     *
     * @return the value of ext_apply_installment_inf.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.UPDATE_TIME
     *
     * @param updateTime the value for ext_apply_installment_inf.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CREATOR_ID
     *
     * @return the value of ext_apply_installment_inf.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CREATOR_ID
     *
     * @param creatorId the value for ext_apply_installment_inf.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.UPDATER_ID
     *
     * @return the value of ext_apply_installment_inf.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.UPDATER_ID
     *
     * @param updaterId the value for ext_apply_installment_inf.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.CREATOR_NAME
     *
     * @return the value of ext_apply_installment_inf.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.CREATOR_NAME
     *
     * @param creatorName the value for ext_apply_installment_inf.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_apply_installment_inf.UPDATER_NAME
     *
     * @return the value of ext_apply_installment_inf.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_apply_installment_inf.UPDATER_NAME
     *
     * @param updaterName the value for ext_apply_installment_inf.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}