package com.jufan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.OWNER_ID
     *
     * @mbggenerated
     */
    private String ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.OWNER_NAME
     *
     * @mbggenerated
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.ACCOUNT_ID
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.IS_SUB_ACCOUNT
     *
     * @mbggenerated
     */
    private String isSubAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.PARENT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    private String parentAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_account.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.ID
     *
     * @return the value of fin_account.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.ID
     *
     * @param id the value for fin_account.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.OWNER_ID
     *
     * @return the value of fin_account.OWNER_ID
     *
     * @mbggenerated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.OWNER_ID
     *
     * @param ownerId the value for fin_account.OWNER_ID
     *
     * @mbggenerated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.OWNER_NAME
     *
     * @return the value of fin_account.OWNER_NAME
     *
     * @mbggenerated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.OWNER_NAME
     *
     * @param ownerName the value for fin_account.OWNER_NAME
     *
     * @mbggenerated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.ACCOUNT_ID
     *
     * @return the value of fin_account.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.ACCOUNT_ID
     *
     * @param accountId the value for fin_account.ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.ACCOUNT_NAME
     *
     * @return the value of fin_account.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.ACCOUNT_NAME
     *
     * @param accountName the value for fin_account.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.IS_SUB_ACCOUNT
     *
     * @return the value of fin_account.IS_SUB_ACCOUNT
     *
     * @mbggenerated
     */
    public String getIsSubAccount() {
        return isSubAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.IS_SUB_ACCOUNT
     *
     * @param isSubAccount the value for fin_account.IS_SUB_ACCOUNT
     *
     * @mbggenerated
     */
    public void setIsSubAccount(String isSubAccount) {
        this.isSubAccount = isSubAccount == null ? null : isSubAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.PARENT_ACCOUNT_ID
     *
     * @return the value of fin_account.PARENT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public String getParentAccountId() {
        return parentAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.PARENT_ACCOUNT_ID
     *
     * @param parentAccountId the value for fin_account.PARENT_ACCOUNT_ID
     *
     * @mbggenerated
     */
    public void setParentAccountId(String parentAccountId) {
        this.parentAccountId = parentAccountId == null ? null : parentAccountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.BALANCE
     *
     * @return the value of fin_account.BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.BALANCE
     *
     * @param balance the value for fin_account.BALANCE
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.STATUS
     *
     * @return the value of fin_account.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.STATUS
     *
     * @param status the value for fin_account.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.NOTE
     *
     * @return the value of fin_account.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.NOTE
     *
     * @param note the value for fin_account.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.CREATE_TIME
     *
     * @return the value of fin_account.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.CREATE_TIME
     *
     * @param createTime the value for fin_account.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.UPDATE_TIME
     *
     * @return the value of fin_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.UPDATE_TIME
     *
     * @param updateTime the value for fin_account.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.CREATOR_ID
     *
     * @return the value of fin_account.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.CREATOR_ID
     *
     * @param creatorId the value for fin_account.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.UPDATER_ID
     *
     * @return the value of fin_account.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.UPDATER_ID
     *
     * @param updaterId the value for fin_account.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.CREATOR_NAME
     *
     * @return the value of fin_account.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.CREATOR_NAME
     *
     * @param creatorName the value for fin_account.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_account.UPDATER_NAME
     *
     * @return the value of fin_account.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_account.UPDATER_NAME
     *
     * @param updaterName the value for fin_account.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}