package com.jufan.entity;

import java.util.Date;

public class FinBankInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ENTITY_ID
     *
     * @mbggenerated
     */
    private String entityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ENTITY_NAME
     *
     * @mbggenerated
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ENTITY_CODE
     *
     * @mbggenerated
     */
    private String entityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ENTITY_TYPE
     *
     * @mbggenerated
     */
    private String entityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    private String accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.BANK_NAME
     *
     * @mbggenerated
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.BANK_FULL_NAME
     *
     * @mbggenerated
     */
    private String bankFullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.BANK_ACCT_NUMBER
     *
     * @mbggenerated
     */
    private String bankAcctNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ACPR_CODES
     *
     * @mbggenerated
     */
    private String acprCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.ACPR_NAME
     *
     * @mbggenerated
     */
    private String acprName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ID
     *
     * @return the value of fin_bank_info.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ID
     *
     * @param id the value for fin_bank_info.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ENTITY_ID
     *
     * @return the value of fin_bank_info.ENTITY_ID
     *
     * @mbggenerated
     */
    public String getEntityId() {
        return entityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ENTITY_ID
     *
     * @param entityId the value for fin_bank_info.ENTITY_ID
     *
     * @mbggenerated
     */
    public void setEntityId(String entityId) {
        this.entityId = entityId == null ? null : entityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ENTITY_NAME
     *
     * @return the value of fin_bank_info.ENTITY_NAME
     *
     * @mbggenerated
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ENTITY_NAME
     *
     * @param entityName the value for fin_bank_info.ENTITY_NAME
     *
     * @mbggenerated
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ENTITY_CODE
     *
     * @return the value of fin_bank_info.ENTITY_CODE
     *
     * @mbggenerated
     */
    public String getEntityCode() {
        return entityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ENTITY_CODE
     *
     * @param entityCode the value for fin_bank_info.ENTITY_CODE
     *
     * @mbggenerated
     */
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode == null ? null : entityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ENTITY_TYPE
     *
     * @return the value of fin_bank_info.ENTITY_TYPE
     *
     * @mbggenerated
     */
    public String getEntityType() {
        return entityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ENTITY_TYPE
     *
     * @param entityType the value for fin_bank_info.ENTITY_TYPE
     *
     * @mbggenerated
     */
    public void setEntityType(String entityType) {
        this.entityType = entityType == null ? null : entityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ACCOUNT_TYPE
     *
     * @return the value of fin_bank_info.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ACCOUNT_TYPE
     *
     * @param accountType the value for fin_bank_info.ACCOUNT_TYPE
     *
     * @mbggenerated
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType == null ? null : accountType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.BANK_CODE
     *
     * @return the value of fin_bank_info.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.BANK_CODE
     *
     * @param bankCode the value for fin_bank_info.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.BANK_NAME
     *
     * @return the value of fin_bank_info.BANK_NAME
     *
     * @mbggenerated
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.BANK_NAME
     *
     * @param bankName the value for fin_bank_info.BANK_NAME
     *
     * @mbggenerated
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.BANK_FULL_NAME
     *
     * @return the value of fin_bank_info.BANK_FULL_NAME
     *
     * @mbggenerated
     */
    public String getBankFullName() {
        return bankFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.BANK_FULL_NAME
     *
     * @param bankFullName the value for fin_bank_info.BANK_FULL_NAME
     *
     * @mbggenerated
     */
    public void setBankFullName(String bankFullName) {
        this.bankFullName = bankFullName == null ? null : bankFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.BANK_ACCT_NUMBER
     *
     * @return the value of fin_bank_info.BANK_ACCT_NUMBER
     *
     * @mbggenerated
     */
    public String getBankAcctNumber() {
        return bankAcctNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.BANK_ACCT_NUMBER
     *
     * @param bankAcctNumber the value for fin_bank_info.BANK_ACCT_NUMBER
     *
     * @mbggenerated
     */
    public void setBankAcctNumber(String bankAcctNumber) {
        this.bankAcctNumber = bankAcctNumber == null ? null : bankAcctNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ACPR_CODES
     *
     * @return the value of fin_bank_info.ACPR_CODES
     *
     * @mbggenerated
     */
    public String getAcprCodes() {
        return acprCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ACPR_CODES
     *
     * @param acprCodes the value for fin_bank_info.ACPR_CODES
     *
     * @mbggenerated
     */
    public void setAcprCodes(String acprCodes) {
        this.acprCodes = acprCodes == null ? null : acprCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.ACPR_NAME
     *
     * @return the value of fin_bank_info.ACPR_NAME
     *
     * @mbggenerated
     */
    public String getAcprName() {
        return acprName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.ACPR_NAME
     *
     * @param acprName the value for fin_bank_info.ACPR_NAME
     *
     * @mbggenerated
     */
    public void setAcprName(String acprName) {
        this.acprName = acprName == null ? null : acprName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.CREATE_TIME
     *
     * @return the value of fin_bank_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.CREATE_TIME
     *
     * @param createTime the value for fin_bank_info.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.UPDATE_TIME
     *
     * @return the value of fin_bank_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.UPDATE_TIME
     *
     * @param updateTime the value for fin_bank_info.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.CREATOR_ID
     *
     * @return the value of fin_bank_info.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.CREATOR_ID
     *
     * @param creatorId the value for fin_bank_info.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.UPDATER_ID
     *
     * @return the value of fin_bank_info.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.UPDATER_ID
     *
     * @param updaterId the value for fin_bank_info.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.CREATOR_NAME
     *
     * @return the value of fin_bank_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.CREATOR_NAME
     *
     * @param creatorName the value for fin_bank_info.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_info.UPDATER_NAME
     *
     * @return the value of fin_bank_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_info.UPDATER_NAME
     *
     * @param updaterName the value for fin_bank_info.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}