package com.jufan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinBankImportDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.IMPORT_INFO_ID
     *
     * @mbggenerated
     */
    private String importInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.PAYEE_BANK
     *
     * @mbggenerated
     */
    private String payeeBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.PAYEE_NAME
     *
     * @mbggenerated
     */
    private String payeeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.PAYEE_ACCOUNT
     *
     * @mbggenerated
     */
    private String payeeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.DRAWEE_BANK
     *
     * @mbggenerated
     */
    private String draweeBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.DRAWEE_NAME
     *
     * @mbggenerated
     */
    private String draweeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.DRAWEE_ACCOUNT
     *
     * @mbggenerated
     */
    private String draweeAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.CURRENCY
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.BANK_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal bankAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.FIX_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal fixAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.VERIFIED_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal verifiedAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.TRANSACTION_ID
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.COMMIT_TIME
     *
     * @mbggenerated
     */
    private Date commitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.IMPORT_TIME
     *
     * @mbggenerated
     */
    private Date importTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_bank_import_detail.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.ID
     *
     * @return the value of fin_bank_import_detail.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.ID
     *
     * @param id the value for fin_bank_import_detail.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.IMPORT_INFO_ID
     *
     * @return the value of fin_bank_import_detail.IMPORT_INFO_ID
     *
     * @mbggenerated
     */
    public String getImportInfoId() {
        return importInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.IMPORT_INFO_ID
     *
     * @param importInfoId the value for fin_bank_import_detail.IMPORT_INFO_ID
     *
     * @mbggenerated
     */
    public void setImportInfoId(String importInfoId) {
        this.importInfoId = importInfoId == null ? null : importInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.PAYEE_BANK
     *
     * @return the value of fin_bank_import_detail.PAYEE_BANK
     *
     * @mbggenerated
     */
    public String getPayeeBank() {
        return payeeBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.PAYEE_BANK
     *
     * @param payeeBank the value for fin_bank_import_detail.PAYEE_BANK
     *
     * @mbggenerated
     */
    public void setPayeeBank(String payeeBank) {
        this.payeeBank = payeeBank == null ? null : payeeBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.PAYEE_NAME
     *
     * @return the value of fin_bank_import_detail.PAYEE_NAME
     *
     * @mbggenerated
     */
    public String getPayeeName() {
        return payeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.PAYEE_NAME
     *
     * @param payeeName the value for fin_bank_import_detail.PAYEE_NAME
     *
     * @mbggenerated
     */
    public void setPayeeName(String payeeName) {
        this.payeeName = payeeName == null ? null : payeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.PAYEE_ACCOUNT
     *
     * @return the value of fin_bank_import_detail.PAYEE_ACCOUNT
     *
     * @mbggenerated
     */
    public String getPayeeAccount() {
        return payeeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.PAYEE_ACCOUNT
     *
     * @param payeeAccount the value for fin_bank_import_detail.PAYEE_ACCOUNT
     *
     * @mbggenerated
     */
    public void setPayeeAccount(String payeeAccount) {
        this.payeeAccount = payeeAccount == null ? null : payeeAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.DRAWEE_BANK
     *
     * @return the value of fin_bank_import_detail.DRAWEE_BANK
     *
     * @mbggenerated
     */
    public String getDraweeBank() {
        return draweeBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.DRAWEE_BANK
     *
     * @param draweeBank the value for fin_bank_import_detail.DRAWEE_BANK
     *
     * @mbggenerated
     */
    public void setDraweeBank(String draweeBank) {
        this.draweeBank = draweeBank == null ? null : draweeBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.DRAWEE_NAME
     *
     * @return the value of fin_bank_import_detail.DRAWEE_NAME
     *
     * @mbggenerated
     */
    public String getDraweeName() {
        return draweeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.DRAWEE_NAME
     *
     * @param draweeName the value for fin_bank_import_detail.DRAWEE_NAME
     *
     * @mbggenerated
     */
    public void setDraweeName(String draweeName) {
        this.draweeName = draweeName == null ? null : draweeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.DRAWEE_ACCOUNT
     *
     * @return the value of fin_bank_import_detail.DRAWEE_ACCOUNT
     *
     * @mbggenerated
     */
    public String getDraweeAccount() {
        return draweeAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.DRAWEE_ACCOUNT
     *
     * @param draweeAccount the value for fin_bank_import_detail.DRAWEE_ACCOUNT
     *
     * @mbggenerated
     */
    public void setDraweeAccount(String draweeAccount) {
        this.draweeAccount = draweeAccount == null ? null : draweeAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.CURRENCY
     *
     * @return the value of fin_bank_import_detail.CURRENCY
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.CURRENCY
     *
     * @param currency the value for fin_bank_import_detail.CURRENCY
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.BANK_AMOUNT
     *
     * @return the value of fin_bank_import_detail.BANK_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getBankAmount() {
        return bankAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.BANK_AMOUNT
     *
     * @param bankAmount the value for fin_bank_import_detail.BANK_AMOUNT
     *
     * @mbggenerated
     */
    public void setBankAmount(BigDecimal bankAmount) {
        this.bankAmount = bankAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.FIX_AMOUNT
     *
     * @return the value of fin_bank_import_detail.FIX_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getFixAmount() {
        return fixAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.FIX_AMOUNT
     *
     * @param fixAmount the value for fin_bank_import_detail.FIX_AMOUNT
     *
     * @mbggenerated
     */
    public void setFixAmount(BigDecimal fixAmount) {
        this.fixAmount = fixAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.AMOUNT
     *
     * @return the value of fin_bank_import_detail.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.AMOUNT
     *
     * @param amount the value for fin_bank_import_detail.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.VERIFIED_AMOUNT
     *
     * @return the value of fin_bank_import_detail.VERIFIED_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getVerifiedAmount() {
        return verifiedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.VERIFIED_AMOUNT
     *
     * @param verifiedAmount the value for fin_bank_import_detail.VERIFIED_AMOUNT
     *
     * @mbggenerated
     */
    public void setVerifiedAmount(BigDecimal verifiedAmount) {
        this.verifiedAmount = verifiedAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.TRANSACTION_ID
     *
     * @return the value of fin_bank_import_detail.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.TRANSACTION_ID
     *
     * @param transactionId the value for fin_bank_import_detail.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.COMMIT_TIME
     *
     * @return the value of fin_bank_import_detail.COMMIT_TIME
     *
     * @mbggenerated
     */
    public Date getCommitTime() {
        return commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.COMMIT_TIME
     *
     * @param commitTime the value for fin_bank_import_detail.COMMIT_TIME
     *
     * @mbggenerated
     */
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.IMPORT_TIME
     *
     * @return the value of fin_bank_import_detail.IMPORT_TIME
     *
     * @mbggenerated
     */
    public Date getImportTime() {
        return importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.IMPORT_TIME
     *
     * @param importTime the value for fin_bank_import_detail.IMPORT_TIME
     *
     * @mbggenerated
     */
    public void setImportTime(Date importTime) {
        this.importTime = importTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.NOTE
     *
     * @return the value of fin_bank_import_detail.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.NOTE
     *
     * @param note the value for fin_bank_import_detail.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.STATUS
     *
     * @return the value of fin_bank_import_detail.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.STATUS
     *
     * @param status the value for fin_bank_import_detail.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.CREATE_TIME
     *
     * @return the value of fin_bank_import_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.CREATE_TIME
     *
     * @param createTime the value for fin_bank_import_detail.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.UPDATE_TIME
     *
     * @return the value of fin_bank_import_detail.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.UPDATE_TIME
     *
     * @param updateTime the value for fin_bank_import_detail.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.CREATOR_ID
     *
     * @return the value of fin_bank_import_detail.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.CREATOR_ID
     *
     * @param creatorId the value for fin_bank_import_detail.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.UPDATER_ID
     *
     * @return the value of fin_bank_import_detail.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.UPDATER_ID
     *
     * @param updaterId the value for fin_bank_import_detail.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.CREATOR_NAME
     *
     * @return the value of fin_bank_import_detail.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.CREATOR_NAME
     *
     * @param creatorName the value for fin_bank_import_detail.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_bank_import_detail.UPDATER_NAME
     *
     * @return the value of fin_bank_import_detail.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_bank_import_detail.UPDATER_NAME
     *
     * @param updaterName the value for fin_bank_import_detail.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}