package com.jufan.entity;

public class FinTransactionLogWithBLOBs extends FinTransactionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CONSUME_REQ
     *
     * @mbggenerated
     */
    private String consumeReq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CONSUME_RESPONSE
     *
     * @mbggenerated
     */
    private String consumeResponse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CONSUME_REQ
     *
     * @return the value of fin_transaction_log.CONSUME_REQ
     *
     * @mbggenerated
     */
    public String getConsumeReq() {
        return consumeReq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CONSUME_REQ
     *
     * @param consumeReq the value for fin_transaction_log.CONSUME_REQ
     *
     * @mbggenerated
     */
    public void setConsumeReq(String consumeReq) {
        this.consumeReq = consumeReq == null ? null : consumeReq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CONSUME_RESPONSE
     *
     * @return the value of fin_transaction_log.CONSUME_RESPONSE
     *
     * @mbggenerated
     */
    public String getConsumeResponse() {
        return consumeResponse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CONSUME_RESPONSE
     *
     * @param consumeResponse the value for fin_transaction_log.CONSUME_RESPONSE
     *
     * @mbggenerated
     */
    public void setConsumeResponse(String consumeResponse) {
        this.consumeResponse = consumeResponse == null ? null : consumeResponse.trim();
    }
}