package com.jufan.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FinTransactionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.MERCHANT_ID
     *
     * @mbggenerated
     */
    private String merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CUSTOMER_ID
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.REF_BIZ_ID
     *
     * @mbggenerated
     */
    private String refBizId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.ORDER_NUMBER
     *
     * @mbggenerated
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.DIRECTION
     *
     * @mbggenerated
     */
    private String direction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.PAY_METHOD
     *
     * @mbggenerated
     */
    private String payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CHANNEL_CODE
     *
     * @mbggenerated
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CURRENCY_CODE
     *
     * @mbggenerated
     */
    private String currencyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.ACC_NAME
     *
     * @mbggenerated
     */
    private String accName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.ACC_NUMBER
     *
     * @mbggenerated
     */
    private String accNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.TRANSACTION_ID
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fin_transaction_log.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.ID
     *
     * @return the value of fin_transaction_log.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.ID
     *
     * @param id the value for fin_transaction_log.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.MERCHANT_ID
     *
     * @return the value of fin_transaction_log.MERCHANT_ID
     *
     * @mbggenerated
     */
    public String getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.MERCHANT_ID
     *
     * @param merchantId the value for fin_transaction_log.MERCHANT_ID
     *
     * @mbggenerated
     */
    public void setMerchantId(String merchantId) {
        this.merchantId = merchantId == null ? null : merchantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CUSTOMER_ID
     *
     * @return the value of fin_transaction_log.CUSTOMER_ID
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CUSTOMER_ID
     *
     * @param customerId the value for fin_transaction_log.CUSTOMER_ID
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.REF_BIZ_ID
     *
     * @return the value of fin_transaction_log.REF_BIZ_ID
     *
     * @mbggenerated
     */
    public String getRefBizId() {
        return refBizId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.REF_BIZ_ID
     *
     * @param refBizId the value for fin_transaction_log.REF_BIZ_ID
     *
     * @mbggenerated
     */
    public void setRefBizId(String refBizId) {
        this.refBizId = refBizId == null ? null : refBizId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.ORDER_NUMBER
     *
     * @return the value of fin_transaction_log.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.ORDER_NUMBER
     *
     * @param orderNumber the value for fin_transaction_log.ORDER_NUMBER
     *
     * @mbggenerated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.DIRECTION
     *
     * @return the value of fin_transaction_log.DIRECTION
     *
     * @mbggenerated
     */
    public String getDirection() {
        return direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.DIRECTION
     *
     * @param direction the value for fin_transaction_log.DIRECTION
     *
     * @mbggenerated
     */
    public void setDirection(String direction) {
        this.direction = direction == null ? null : direction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.PAY_METHOD
     *
     * @return the value of fin_transaction_log.PAY_METHOD
     *
     * @mbggenerated
     */
    public String getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.PAY_METHOD
     *
     * @param payMethod the value for fin_transaction_log.PAY_METHOD
     *
     * @mbggenerated
     */
    public void setPayMethod(String payMethod) {
        this.payMethod = payMethod == null ? null : payMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CHANNEL_CODE
     *
     * @return the value of fin_transaction_log.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CHANNEL_CODE
     *
     * @param channelCode the value for fin_transaction_log.CHANNEL_CODE
     *
     * @mbggenerated
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CURRENCY_CODE
     *
     * @return the value of fin_transaction_log.CURRENCY_CODE
     *
     * @mbggenerated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CURRENCY_CODE
     *
     * @param currencyCode the value for fin_transaction_log.CURRENCY_CODE
     *
     * @mbggenerated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.ACC_NAME
     *
     * @return the value of fin_transaction_log.ACC_NAME
     *
     * @mbggenerated
     */
    public String getAccName() {
        return accName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.ACC_NAME
     *
     * @param accName the value for fin_transaction_log.ACC_NAME
     *
     * @mbggenerated
     */
    public void setAccName(String accName) {
        this.accName = accName == null ? null : accName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.ACC_NUMBER
     *
     * @return the value of fin_transaction_log.ACC_NUMBER
     *
     * @mbggenerated
     */
    public String getAccNumber() {
        return accNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.ACC_NUMBER
     *
     * @param accNumber the value for fin_transaction_log.ACC_NUMBER
     *
     * @mbggenerated
     */
    public void setAccNumber(String accNumber) {
        this.accNumber = accNumber == null ? null : accNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.TRANSACTION_ID
     *
     * @return the value of fin_transaction_log.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.TRANSACTION_ID
     *
     * @param transactionId the value for fin_transaction_log.TRANSACTION_ID
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.AMOUNT
     *
     * @return the value of fin_transaction_log.AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.AMOUNT
     *
     * @param amount the value for fin_transaction_log.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.NOTE
     *
     * @return the value of fin_transaction_log.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.NOTE
     *
     * @param note the value for fin_transaction_log.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.STATUS
     *
     * @return the value of fin_transaction_log.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.STATUS
     *
     * @param status the value for fin_transaction_log.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CREATE_TIME
     *
     * @return the value of fin_transaction_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CREATE_TIME
     *
     * @param createTime the value for fin_transaction_log.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.UPDATE_TIME
     *
     * @return the value of fin_transaction_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.UPDATE_TIME
     *
     * @param updateTime the value for fin_transaction_log.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CREATOR_ID
     *
     * @return the value of fin_transaction_log.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CREATOR_ID
     *
     * @param creatorId the value for fin_transaction_log.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.UPDATER_ID
     *
     * @return the value of fin_transaction_log.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.UPDATER_ID
     *
     * @param updaterId the value for fin_transaction_log.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.CREATOR_NAME
     *
     * @return the value of fin_transaction_log.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.CREATOR_NAME
     *
     * @param creatorName the value for fin_transaction_log.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fin_transaction_log.UPDATER_NAME
     *
     * @return the value of fin_transaction_log.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fin_transaction_log.UPDATER_NAME
     *
     * @param updaterName the value for fin_transaction_log.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}