package com.jufan.entity;

public class OrderPayoutWithBLOBs extends OrderPayout {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payout.REQUEST_RAW
     *
     * @mbggenerated
     */
    private String requestRaw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payout.RESPONSE_RAW
     *
     * @mbggenerated
     */
    private String responseRaw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_payout.RESPONSE_RAW_CALLBACK
     *
     * @mbggenerated
     */
    private String responseRawCallback;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payout.REQUEST_RAW
     *
     * @return the value of order_payout.REQUEST_RAW
     *
     * @mbggenerated
     */
    public String getRequestRaw() {
        return requestRaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payout.REQUEST_RAW
     *
     * @param requestRaw the value for order_payout.REQUEST_RAW
     *
     * @mbggenerated
     */
    public void setRequestRaw(String requestRaw) {
        this.requestRaw = requestRaw == null ? null : requestRaw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payout.RESPONSE_RAW
     *
     * @return the value of order_payout.RESPONSE_RAW
     *
     * @mbggenerated
     */
    public String getResponseRaw() {
        return responseRaw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payout.RESPONSE_RAW
     *
     * @param responseRaw the value for order_payout.RESPONSE_RAW
     *
     * @mbggenerated
     */
    public void setResponseRaw(String responseRaw) {
        this.responseRaw = responseRaw == null ? null : responseRaw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_payout.RESPONSE_RAW_CALLBACK
     *
     * @return the value of order_payout.RESPONSE_RAW_CALLBACK
     *
     * @mbggenerated
     */
    public String getResponseRawCallback() {
        return responseRawCallback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_payout.RESPONSE_RAW_CALLBACK
     *
     * @param responseRawCallback the value for order_payout.RESPONSE_RAW_CALLBACK
     *
     * @mbggenerated
     */
    public void setResponseRawCallback(String responseRawCallback) {
        this.responseRawCallback = responseRawCallback == null ? null : responseRawCallback.trim();
    }
}