package com.jufan.entity;

import java.util.Date;

public class RepayplanExchange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.NEW_BATCH_ID
     *
     * @mbggenerated
     */
    private String newBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.HISTORY_BATCH_ID
     *
     * @mbggenerated
     */
    private String historyBatchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.CONTRACT_ID
     *
     * @mbggenerated
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.PRICING_MODEL_ID
     *
     * @mbggenerated
     */
    private String pricingModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.IS_VALID
     *
     * @mbggenerated
     */
    private String isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column repayplan_exchange.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.ID
     *
     * @return the value of repayplan_exchange.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.ID
     *
     * @param id the value for repayplan_exchange.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.NEW_BATCH_ID
     *
     * @return the value of repayplan_exchange.NEW_BATCH_ID
     *
     * @mbggenerated
     */
    public String getNewBatchId() {
        return newBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.NEW_BATCH_ID
     *
     * @param newBatchId the value for repayplan_exchange.NEW_BATCH_ID
     *
     * @mbggenerated
     */
    public void setNewBatchId(String newBatchId) {
        this.newBatchId = newBatchId == null ? null : newBatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.HISTORY_BATCH_ID
     *
     * @return the value of repayplan_exchange.HISTORY_BATCH_ID
     *
     * @mbggenerated
     */
    public String getHistoryBatchId() {
        return historyBatchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.HISTORY_BATCH_ID
     *
     * @param historyBatchId the value for repayplan_exchange.HISTORY_BATCH_ID
     *
     * @mbggenerated
     */
    public void setHistoryBatchId(String historyBatchId) {
        this.historyBatchId = historyBatchId == null ? null : historyBatchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.CONTRACT_ID
     *
     * @return the value of repayplan_exchange.CONTRACT_ID
     *
     * @mbggenerated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.CONTRACT_ID
     *
     * @param contractId the value for repayplan_exchange.CONTRACT_ID
     *
     * @mbggenerated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.PRICING_MODEL_ID
     *
     * @return the value of repayplan_exchange.PRICING_MODEL_ID
     *
     * @mbggenerated
     */
    public String getPricingModelId() {
        return pricingModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.PRICING_MODEL_ID
     *
     * @param pricingModelId the value for repayplan_exchange.PRICING_MODEL_ID
     *
     * @mbggenerated
     */
    public void setPricingModelId(String pricingModelId) {
        this.pricingModelId = pricingModelId == null ? null : pricingModelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.IS_VALID
     *
     * @return the value of repayplan_exchange.IS_VALID
     *
     * @mbggenerated
     */
    public String getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.IS_VALID
     *
     * @param isValid the value for repayplan_exchange.IS_VALID
     *
     * @mbggenerated
     */
    public void setIsValid(String isValid) {
        this.isValid = isValid == null ? null : isValid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.NOTE
     *
     * @return the value of repayplan_exchange.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.NOTE
     *
     * @param note the value for repayplan_exchange.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.CREATE_TIME
     *
     * @return the value of repayplan_exchange.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.CREATE_TIME
     *
     * @param createTime the value for repayplan_exchange.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.UPDATE_TIME
     *
     * @return the value of repayplan_exchange.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.UPDATE_TIME
     *
     * @param updateTime the value for repayplan_exchange.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.CREATOR_ID
     *
     * @return the value of repayplan_exchange.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.CREATOR_ID
     *
     * @param creatorId the value for repayplan_exchange.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.UPDATER_ID
     *
     * @return the value of repayplan_exchange.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.UPDATER_ID
     *
     * @param updaterId the value for repayplan_exchange.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.CREATOR_NAME
     *
     * @return the value of repayplan_exchange.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.CREATOR_NAME
     *
     * @param creatorName the value for repayplan_exchange.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column repayplan_exchange.UPDATER_NAME
     *
     * @return the value of repayplan_exchange.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column repayplan_exchange.UPDATER_NAME
     *
     * @param updaterName the value for repayplan_exchange.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}