package com.jufan.entity;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.REAL_NAME
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ADDRESS
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ADVANCED_PASSWORD
     *
     * @mbggenerated
     */
    private String advancedPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ID_CARD_TYPE
     *
     * @mbggenerated
     */
    private String idCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.ID_CARD_NUMBER
     *
     * @mbggenerated
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APCR_CODES
     *
     * @mbggenerated
     */
    private String apcrCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APCR_NAMES
     *
     * @mbggenerated
     */
    private String apcrNames;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.PWD_VALID_THRU
     *
     * @mbggenerated
     */
    private Date pwdValidThru;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APPROVE_STATUS
     *
     * @mbggenerated
     */
    private Integer approveStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APPROVE_OPERATOR_ID
     *
     * @mbggenerated
     */
    private String approveOperatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APPROVE_OPERATOR_CODE
     *
     * @mbggenerated
     */
    private String approveOperatorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.APPROVE_DATE
     *
     * @mbggenerated
     */
    private Date approveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.TOKEN_KEY
     *
     * @mbggenerated
     */
    private String tokenKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.SIGN
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATOR_ID
     *
     * @mbggenerated
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATER_ID
     *
     * @mbggenerated
     */
    private String updaterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.CREATOR_NAME
     *
     * @mbggenerated
     */
    private String creatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.UPDATER_NAME
     *
     * @mbggenerated
     */
    private String updaterName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID
     *
     * @return the value of sys_user.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID
     *
     * @param id the value for sys_user.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NAME
     *
     * @return the value of sys_user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NAME
     *
     * @param name the value for sys_user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.REAL_NAME
     *
     * @return the value of sys_user.REAL_NAME
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.REAL_NAME
     *
     * @param realName the value for sys_user.REAL_NAME
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PHONE
     *
     * @return the value of sys_user.PHONE
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PHONE
     *
     * @param phone the value for sys_user.PHONE
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ADDRESS
     *
     * @return the value of sys_user.ADDRESS
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ADDRESS
     *
     * @param address the value for sys_user.ADDRESS
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PASSWORD
     *
     * @return the value of sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PASSWORD
     *
     * @param password the value for sys_user.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ADVANCED_PASSWORD
     *
     * @return the value of sys_user.ADVANCED_PASSWORD
     *
     * @mbggenerated
     */
    public String getAdvancedPassword() {
        return advancedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ADVANCED_PASSWORD
     *
     * @param advancedPassword the value for sys_user.ADVANCED_PASSWORD
     *
     * @mbggenerated
     */
    public void setAdvancedPassword(String advancedPassword) {
        this.advancedPassword = advancedPassword == null ? null : advancedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.EMAIL
     *
     * @return the value of sys_user.EMAIL
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.EMAIL
     *
     * @param email the value for sys_user.EMAIL
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID_CARD_TYPE
     *
     * @return the value of sys_user.ID_CARD_TYPE
     *
     * @mbggenerated
     */
    public String getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID_CARD_TYPE
     *
     * @param idCardType the value for sys_user.ID_CARD_TYPE
     *
     * @mbggenerated
     */
    public void setIdCardType(String idCardType) {
        this.idCardType = idCardType == null ? null : idCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.ID_CARD_NUMBER
     *
     * @return the value of sys_user.ID_CARD_NUMBER
     *
     * @mbggenerated
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.ID_CARD_NUMBER
     *
     * @param idCardNumber the value for sys_user.ID_CARD_NUMBER
     *
     * @mbggenerated
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber == null ? null : idCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.STATUS
     *
     * @return the value of sys_user.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.STATUS
     *
     * @param status the value for sys_user.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.NOTE
     *
     * @return the value of sys_user.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.NOTE
     *
     * @param note the value for sys_user.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APCR_CODES
     *
     * @return the value of sys_user.APCR_CODES
     *
     * @mbggenerated
     */
    public String getApcrCodes() {
        return apcrCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APCR_CODES
     *
     * @param apcrCodes the value for sys_user.APCR_CODES
     *
     * @mbggenerated
     */
    public void setApcrCodes(String apcrCodes) {
        this.apcrCodes = apcrCodes == null ? null : apcrCodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APCR_NAMES
     *
     * @return the value of sys_user.APCR_NAMES
     *
     * @mbggenerated
     */
    public String getApcrNames() {
        return apcrNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APCR_NAMES
     *
     * @param apcrNames the value for sys_user.APCR_NAMES
     *
     * @mbggenerated
     */
    public void setApcrNames(String apcrNames) {
        this.apcrNames = apcrNames == null ? null : apcrNames.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.PWD_VALID_THRU
     *
     * @return the value of sys_user.PWD_VALID_THRU
     *
     * @mbggenerated
     */
    public Date getPwdValidThru() {
        return pwdValidThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.PWD_VALID_THRU
     *
     * @param pwdValidThru the value for sys_user.PWD_VALID_THRU
     *
     * @mbggenerated
     */
    public void setPwdValidThru(Date pwdValidThru) {
        this.pwdValidThru = pwdValidThru;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APPROVE_STATUS
     *
     * @return the value of sys_user.APPROVE_STATUS
     *
     * @mbggenerated
     */
    public Integer getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APPROVE_STATUS
     *
     * @param approveStatus the value for sys_user.APPROVE_STATUS
     *
     * @mbggenerated
     */
    public void setApproveStatus(Integer approveStatus) {
        this.approveStatus = approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APPROVE_OPERATOR_ID
     *
     * @return the value of sys_user.APPROVE_OPERATOR_ID
     *
     * @mbggenerated
     */
    public String getApproveOperatorId() {
        return approveOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APPROVE_OPERATOR_ID
     *
     * @param approveOperatorId the value for sys_user.APPROVE_OPERATOR_ID
     *
     * @mbggenerated
     */
    public void setApproveOperatorId(String approveOperatorId) {
        this.approveOperatorId = approveOperatorId == null ? null : approveOperatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APPROVE_OPERATOR_CODE
     *
     * @return the value of sys_user.APPROVE_OPERATOR_CODE
     *
     * @mbggenerated
     */
    public String getApproveOperatorCode() {
        return approveOperatorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APPROVE_OPERATOR_CODE
     *
     * @param approveOperatorCode the value for sys_user.APPROVE_OPERATOR_CODE
     *
     * @mbggenerated
     */
    public void setApproveOperatorCode(String approveOperatorCode) {
        this.approveOperatorCode = approveOperatorCode == null ? null : approveOperatorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.APPROVE_DATE
     *
     * @return the value of sys_user.APPROVE_DATE
     *
     * @mbggenerated
     */
    public Date getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.APPROVE_DATE
     *
     * @param approveDate the value for sys_user.APPROVE_DATE
     *
     * @mbggenerated
     */
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.TOKEN_KEY
     *
     * @return the value of sys_user.TOKEN_KEY
     *
     * @mbggenerated
     */
    public String getTokenKey() {
        return tokenKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.TOKEN_KEY
     *
     * @param tokenKey the value for sys_user.TOKEN_KEY
     *
     * @mbggenerated
     */
    public void setTokenKey(String tokenKey) {
        this.tokenKey = tokenKey == null ? null : tokenKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.SIGN
     *
     * @return the value of sys_user.SIGN
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.SIGN
     *
     * @param sign the value for sys_user.SIGN
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATE_TIME
     *
     * @return the value of sys_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATE_TIME
     *
     * @param createTime the value for sys_user.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATE_TIME
     *
     * @return the value of sys_user.UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATE_TIME
     *
     * @param updateTime the value for sys_user.UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATOR_ID
     *
     * @return the value of sys_user.CREATOR_ID
     *
     * @mbggenerated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATOR_ID
     *
     * @param creatorId the value for sys_user.CREATOR_ID
     *
     * @mbggenerated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATER_ID
     *
     * @return the value of sys_user.UPDATER_ID
     *
     * @mbggenerated
     */
    public String getUpdaterId() {
        return updaterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATER_ID
     *
     * @param updaterId the value for sys_user.UPDATER_ID
     *
     * @mbggenerated
     */
    public void setUpdaterId(String updaterId) {
        this.updaterId = updaterId == null ? null : updaterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.CREATOR_NAME
     *
     * @return the value of sys_user.CREATOR_NAME
     *
     * @mbggenerated
     */
    public String getCreatorName() {
        return creatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.CREATOR_NAME
     *
     * @param creatorName the value for sys_user.CREATOR_NAME
     *
     * @mbggenerated
     */
    public void setCreatorName(String creatorName) {
        this.creatorName = creatorName == null ? null : creatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.UPDATER_NAME
     *
     * @return the value of sys_user.UPDATER_NAME
     *
     * @mbggenerated
     */
    public String getUpdaterName() {
        return updaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.UPDATER_NAME
     *
     * @param updaterName the value for sys_user.UPDATER_NAME
     *
     * @mbggenerated
     */
    public void setUpdaterName(String updaterName) {
        this.updaterName = updaterName == null ? null : updaterName.trim();
    }
}