package com.jufan.entity;

import java.util.Date;

public class TimeTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_test.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_test.TEST_DATE
     *
     * @mbggenerated
     */
    private Date testDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_test.TEST_TIMESTAMP
     *
     * @mbggenerated
     */
    private Date testTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_test.TEST_TEXT
     *
     * @mbggenerated
     */
    private String testText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_test.ID
     *
     * @return the value of time_test.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_test.ID
     *
     * @param id the value for time_test.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_test.TEST_DATE
     *
     * @return the value of time_test.TEST_DATE
     *
     * @mbggenerated
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_test.TEST_DATE
     *
     * @param testDate the value for time_test.TEST_DATE
     *
     * @mbggenerated
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_test.TEST_TIMESTAMP
     *
     * @return the value of time_test.TEST_TIMESTAMP
     *
     * @mbggenerated
     */
    public Date getTestTimestamp() {
        return testTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_test.TEST_TIMESTAMP
     *
     * @param testTimestamp the value for time_test.TEST_TIMESTAMP
     *
     * @mbggenerated
     */
    public void setTestTimestamp(Date testTimestamp) {
        this.testTimestamp = testTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_test.TEST_TEXT
     *
     * @return the value of time_test.TEST_TEXT
     *
     * @mbggenerated
     */
    public String getTestText() {
        return testText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_test.TEST_TEXT
     *
     * @param testText the value for time_test.TEST_TEXT
     *
     * @mbggenerated
     */
    public void setTestText(String testText) {
        this.testText = testText == null ? null : testText.trim();
    }
}