package com.jufan.entity;

import java.util.Date;

public class TpSms {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.ID
	 *
	 * @mbggenerated
	 */
	private String id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.CUSTOMER_ID
	 *
	 * @mbggenerated
	 */
	private String customerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.CONTRACT_ID
	 *
	 * @mbggenerated
	 */
	private String contractId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.NUMBER
	 *
	 * @mbggenerated
	 */
	private String number;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.CONTENT
	 *
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.PROVIDER
	 *
	 * @mbggenerated
	 */
	private String provider;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.SMS_PROVIDER
	 *
	 * @mbggenerated
	 */
	private String smsProvider;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.SMS_PARAM
	 *
	 * @mbggenerated
	 */
	private String smsParam;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.STATUS
	 *
	 * @mbggenerated
	 */
	private String status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.RETRY_COUNT
	 *
	 * @mbggenerated
	 */
	private Integer retryCount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.NOTE
	 *
	 * @mbggenerated
	 */
	private String note;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.SEND_TIME
	 *
	 * @mbggenerated
	 */
	private Date sendTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.ACTUAL_SEND_TIME
	 *
	 * @mbggenerated
	 */
	private Date actualSendTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.CREATOR_ID
	 *
	 * @mbggenerated
	 */
	private String creatorId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tp_sms.UPDATER_ID
	 *
	 * @mbggenerated
	 */
	private String updaterId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.ID
	 *
	 * @return the value of tp_sms.ID
	 *
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.ID
	 *
	 * @param id
	 *            the value for tp_sms.ID
	 *
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.CUSTOMER_ID
	 *
	 * @return the value of tp_sms.CUSTOMER_ID
	 *
	 * @mbggenerated
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.CUSTOMER_ID
	 *
	 * @param customerId
	 *            the value for tp_sms.CUSTOMER_ID
	 *
	 * @mbggenerated
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.CONTRACT_ID
	 *
	 * @return the value of tp_sms.CONTRACT_ID
	 *
	 * @mbggenerated
	 */
	public String getContractId() {
		return contractId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.CONTRACT_ID
	 *
	 * @param contractId
	 *            the value for tp_sms.CONTRACT_ID
	 *
	 * @mbggenerated
	 */
	public void setContractId(String contractId) {
		this.contractId = contractId == null ? null : contractId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.NUMBER
	 *
	 * @return the value of tp_sms.NUMBER
	 *
	 * @mbggenerated
	 */
	public String getNumber() {
		return number;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.NUMBER
	 *
	 * @param number
	 *            the value for tp_sms.NUMBER
	 *
	 * @mbggenerated
	 */
	public void setNumber(String number) {
		this.number = number == null ? null : number.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.CONTENT
	 *
	 * @return the value of tp_sms.CONTENT
	 *
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.CONTENT
	 *
	 * @param content
	 *            the value for tp_sms.CONTENT
	 *
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.PROVIDER
	 *
	 * @return the value of tp_sms.PROVIDER
	 *
	 * @mbggenerated
	 */
	public String getProvider() {
		return provider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.PROVIDER
	 *
	 * @param provider
	 *            the value for tp_sms.PROVIDER
	 *
	 * @mbggenerated
	 */
	public void setProvider(String provider) {
		this.provider = provider == null ? null : provider.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.SMS_PROVIDER
	 *
	 * @return the value of tp_sms.SMS_PROVIDER
	 *
	 * @mbggenerated
	 */
	public String getSmsProvider() {
		return smsProvider;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.SMS_PROVIDER
	 *
	 * @param smsProvider
	 *            the value for tp_sms.SMS_PROVIDER
	 *
	 * @mbggenerated
	 */
	public void setSmsProvider(String smsProvider) {
		this.smsProvider = smsProvider == null ? null : smsProvider.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.SMS_PARAM
	 *
	 * @return the value of tp_sms.SMS_PARAM
	 *
	 * @mbggenerated
	 */
	public String getSmsParam() {
		return smsParam;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.SMS_PARAM
	 *
	 * @param smsParam
	 *            the value for tp_sms.SMS_PARAM
	 *
	 * @mbggenerated
	 */
	public void setSmsParam(String smsParam) {
		this.smsParam = smsParam == null ? null : smsParam.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.STATUS
	 *
	 * @return the value of tp_sms.STATUS
	 *
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.STATUS
	 *
	 * @param status
	 *            the value for tp_sms.STATUS
	 *
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.RETRY_COUNT
	 *
	 * @return the value of tp_sms.RETRY_COUNT
	 *
	 * @mbggenerated
	 */
	public Integer getRetryCount() {
		return retryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.RETRY_COUNT
	 *
	 * @param retryCount
	 *            the value for tp_sms.RETRY_COUNT
	 *
	 * @mbggenerated
	 */
	public void setRetryCount(Integer retryCount) {
		this.retryCount = retryCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.NOTE
	 *
	 * @return the value of tp_sms.NOTE
	 *
	 * @mbggenerated
	 */
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.NOTE
	 *
	 * @param note
	 *            the value for tp_sms.NOTE
	 *
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.SEND_TIME
	 *
	 * @return the value of tp_sms.SEND_TIME
	 *
	 * @mbggenerated
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.SEND_TIME
	 *
	 * @param sendTime
	 *            the value for tp_sms.SEND_TIME
	 *
	 * @mbggenerated
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.ACTUAL_SEND_TIME
	 *
	 * @return the value of tp_sms.ACTUAL_SEND_TIME
	 *
	 * @mbggenerated
	 */
	public Date getActualSendTime() {
		return actualSendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.ACTUAL_SEND_TIME
	 *
	 * @param actualSendTime
	 *            the value for tp_sms.ACTUAL_SEND_TIME
	 *
	 * @mbggenerated
	 */
	public void setActualSendTime(Date actualSendTime) {
		this.actualSendTime = actualSendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.CREATE_TIME
	 *
	 * @return the value of tp_sms.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.CREATE_TIME
	 *
	 * @param createTime
	 *            the value for tp_sms.CREATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.UPDATE_TIME
	 *
	 * @return the value of tp_sms.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.UPDATE_TIME
	 *
	 * @param updateTime
	 *            the value for tp_sms.UPDATE_TIME
	 *
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.CREATOR_ID
	 *
	 * @return the value of tp_sms.CREATOR_ID
	 *
	 * @mbggenerated
	 */
	public String getCreatorId() {
		return creatorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.CREATOR_ID
	 *
	 * @param creatorId
	 *            the value for tp_sms.CREATOR_ID
	 *
	 * @mbggenerated
	 */
	public void setCreatorId(String creatorId) {
		this.creatorId = creatorId == null ? null : creatorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column tp_sms.UPDATER_ID
	 *
	 * @return the value of tp_sms.UPDATER_ID
	 *
	 * @mbggenerated
	 */
	public String getUpdaterId() {
		return updaterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column tp_sms.UPDATER_ID
	 *
	 * @param updaterId
	 *            the value for tp_sms.UPDATER_ID
	 *
	 * @mbggenerated
	 */
	public void setUpdaterId(String updaterId) {
		this.updaterId = updaterId == null ? null : updaterId.trim();
	}

	public TpSms(String id, String customerId, String contractId, String number, String content, String provider,
			String smsProvider, String smsParam, String status, Integer retryCount, String note, Date sendTime,
			Date actualSendTime, Date createTime, Date updateTime, String creatorId, String updaterId) {
		super();
		this.id = id;
		this.customerId = customerId;
		this.contractId = contractId;
		this.number = number;
		this.content = content;
		this.provider = provider;
		this.smsProvider = smsProvider;
		this.smsParam = smsParam;
		this.status = status;
		this.retryCount = retryCount;
		this.note = note;
		this.sendTime = sendTime;
		this.actualSendTime = actualSendTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.creatorId = creatorId;
		this.updaterId = updaterId;
	}

	public TpSms() {
		super();
	}

}